"""Extract 42 historical events from the docx dump into 3 CSVs + 2 audit markdowns.

Source: D:/GEDS/backend/data/raw/docx_dump.json (generated by python-docx from
the user-provided D:/GEDS-Historical-Economic-Disruption-Dataset-2000-2026.docx).

Outputs:
  backend/data/csv/historical_events_expanded.csv
  backend/data/csv/validation_targets.csv
  backend/data/csv/event_to_graph_mapping.csv
  docs/DATA_AUDIT.md
  docs/DATA_SUMMARY.md

Rules followed (per the request):
  - Percentages as numeric values
  - Countries as ISO3 codes
  - Sectors using a fixed taxonomy
  - Missing values as empty (CSV NULL semantics)
  - Confidence 1-5 integer
  - No invented values: if a field is not in the source, it stays empty.
  - Where the source gives a range (e.g. "−40–60%"), midpoint is taken
    and a flag is recorded in the audit.
"""

from __future__ import annotations

import csv
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
DUMP = REPO / "backend" / "data" / "raw" / "docx_dump.json"
CSV_DIR = REPO / "backend" / "data" / "csv"
DOCS_DIR = REPO / "docs"
CSV_DIR.mkdir(parents=True, exist_ok=True)
DOCS_DIR.mkdir(parents=True, exist_ok=True)


# ── normalization tables ────────────────────────────────────────────────────

COUNTRY_TO_ISO3 = {
    "usa": "USA", "u.s.": "USA", "us": "USA", "united states": "USA", "america": "USA",
    "uk": "GBR", "u.k.": "GBR", "united kingdom": "GBR", "britain": "GBR", "great britain": "GBR",
    "germany": "DEU", "deutschland": "DEU",
    "france": "FRA", "japan": "JPN",
    "south korea": "KOR", "korea": "KOR", "republic of korea": "KOR",
    "north korea": "PRK", "dprk": "PRK",
    "china": "CHN", "prc": "CHN", "people's republic of china": "CHN",
    "hong kong": "HKG", "taiwan": "TWN", "macau": "MAC",
    "russia": "RUS", "russian federation": "RUS",
    "ukraine": "UKR",
    "argentina": "ARG", "brazil": "BRA", "mexico": "MEX", "canada": "CAN",
    "chile": "CHL", "peru": "PER", "venezuela": "VEN", "colombia": "COL",
    "spain": "ESP", "italy": "ITA", "portugal": "PRT", "greece": "GRC",
    "ireland": "IRL", "netherlands": "NLD", "belgium": "BEL", "luxembourg": "LUX",
    "austria": "AUT", "switzerland": "CHE", "sweden": "SWE", "norway": "NOR",
    "finland": "FIN", "denmark": "DNK", "iceland": "ISL", "poland": "POL",
    "czech republic": "CZE", "czechia": "CZE", "hungary": "HUN", "romania": "ROU",
    "bulgaria": "BGR", "slovakia": "SVK", "slovenia": "SVN", "croatia": "HRV",
    "estonia": "EST", "latvia": "LVA", "lithuania": "LTU",
    "turkey": "TUR", "türkiye": "TUR", "israel": "ISR", "egypt": "EGY",
    "saudi arabia": "SAU", "uae": "ARE", "united arab emirates": "ARE",
    "iran": "IRN", "iraq": "IRQ", "syria": "SYR", "lebanon": "LBN",
    "jordan": "JOR", "yemen": "YEM", "qatar": "QAT", "kuwait": "KWT",
    "bahrain": "BHR", "oman": "OMN",
    "india": "IND", "pakistan": "PAK", "bangladesh": "BGD",
    "sri lanka": "LKA", "nepal": "NPL", "bhutan": "BTN",
    "myanmar": "MMR", "burma": "MMR", "afghanistan": "AFG",
    "indonesia": "IDN", "malaysia": "MYS", "singapore": "SGP",
    "thailand": "THA", "vietnam": "VNM", "viet nam": "VNM",
    "philippines": "PHL", "cambodia": "KHM", "laos": "LAO", "brunei": "BRN",
    "australia": "AUS", "new zealand": "NZL", "papua new guinea": "PNG",
    "south africa": "ZAF", "nigeria": "NGA", "kenya": "KEN", "ethiopia": "ETH",
    "morocco": "MAR", "algeria": "DZA", "tunisia": "TUN", "libya": "LBY",
    "sudan": "SDN", "ghana": "GHA", "angola": "AGO",
    "haiti": "HTI", "dominican republic": "DOM", "cuba": "CUB",
    "puerto rico": "PRI", "jamaica": "JAM", "bahamas": "BHS",
    "maldives": "MDV",
    "palestine": "PSE", "gaza": "PSE",
    # Added 2026-05-24 to cover docx aggregates flagged in DATA_AUDIT.md
    "uruguay": "URY", "bolivia": "BOL", "somalia": "SOM", "seychelles": "SYC",
    "cyprus": "CYP", "panama": "PAN",
}

# Aggregate region names → list of representative ISO3 codes.
# Source: docx repeatedly uses "EU", "Eurozone", "Sub-Saharan Africa", etc.
# We expand to the top economies in each region so propagation has anchor
# nodes. Audit records the original aggregate term so traceability is kept.
REGION_TO_ISO3 = {
    "eu": ["DEU", "FRA", "ITA", "ESP", "NLD", "POL", "BEL"],
    "eu27": ["DEU", "FRA", "ITA", "ESP", "NLD", "POL", "BEL"],
    "european union": ["DEU", "FRA", "ITA", "ESP", "NLD", "POL", "BEL"],
    "eurozone": ["DEU", "FRA", "ITA", "ESP", "NLD", "BEL", "IRL"],
    "broader eurozone": ["DEU", "FRA", "ITA", "ESP", "NLD", "BEL", "IRL"],
    "mena": ["SAU", "EGY", "ARE", "ISR", "TUR"],
    "broader mena region": ["SAU", "EGY", "ARE", "ISR", "TUR"],
    "regional mena": ["SAU", "EGY", "ARE", "ISR", "TUR"],
    "middle east": ["SAU", "ARE", "ISR", "IRN", "IRQ"],
    "east africa": ["KEN", "ETH", "TZA", "UGA"],
    "sub-saharan africa": ["NGA", "ZAF", "KEN", "ETH", "AGO"],
    "south asia": ["IND", "PAK", "BGD", "LKA"],
    "southeast asia": ["IDN", "THA", "VNM", "MYS", "PHL", "SGP"],
    "latin america": ["BRA", "MEX", "ARG", "COL", "CHL"],
    "eastern europe": ["POL", "ROU", "HUN", "CZE"],
    "caribbean islands": ["DOM", "HTI", "JAM", "BHS"],
    "frontier markets": ["PAK", "GHA", "LKA", "ZMB"],
}

# Aggregate terms that DO NOT expand to specific ISO3 — recorded as scope flag.
SCOPE_GLOBAL_TERMS = {
    "global", "worldwide", "world",
    "global via trade channels", "global via oil markets",
    "global via risk sentiment", "commodity demand",
    "commodity exporters via demand channel",
    "emerging markets with usd-denominated debt",
    "emerging markets",
    "most severely: usa", "most affected: eu",
    "regional aid economy",
}

# Sector taxonomy: fixed list. New ones added beyond GEDS-engine industries
# are flagged in the audit as "not in current GEDS graph".
SECTOR_TAXONOMY = {
    # GEDS-engine industries
    "semiconductors": "semiconductors",
    "semiconductor": "semiconductors",
    "chips": "semiconductors",
    "chip": "semiconductors",
    "automotive": "automotive",
    "auto": "automotive",
    "autos": "automotive",
    "electronics": "electronics",
    "consumer electronics": "electronics",
    "aerospace": "aerospace",
    "aircraft": "aerospace",
    "aviation": "aerospace",
    "consumer goods": "consumer_goods",
    "retail": "consumer_goods",
    "shipping": "shipping",
    "maritime": "shipping",
    "logistics": "shipping",
    "ports": "shipping",
    "energy": "energy",
    "oil": "energy",
    "gas": "energy",
    "oil & gas": "energy",
    "petroleum": "energy",
    "lng": "energy",
    # Extended (not in current GEDS node set)
    "technology": "technology",
    "tech": "technology",
    "telecommunications": "telecommunications",
    "telecom": "telecommunications",
    "telecoms": "telecommunications",
    "finance": "financial",
    "financial": "financial",
    "financial services": "financial",
    "banking": "financial",
    "venture capital": "financial",
    "real estate": "real_estate",
    "construction": "construction",
    "property": "real_estate",
    "agriculture": "agriculture",
    "agricultural": "agriculture",
    "food": "agriculture",
    "wheat": "agriculture",
    "grain": "agriculture",
    "grains": "agriculture",
    "fisheries": "agriculture",
    "tourism": "tourism",
    "travel": "tourism",
    "hospitality": "tourism",
    "manufacturing": "manufacturing",
    "industrial": "manufacturing",
    "healthcare": "healthcare",
    "pharmaceuticals": "healthcare",
    "pharma": "healthcare",
    "mining": "mining",
    "commodities": "commodities",
    "chemicals": "chemicals",
    "textiles": "textiles",
    "apparel": "textiles",
    "metals": "metals",
    "steel": "metals",
    "fertilizer": "chemicals",
    "fertilizers": "chemicals",
    "insurance": "financial",
    "insurers": "financial",
    # Added 2026-05-24 to cover unmapped sector terms in DATA_AUDIT.md
    "defense": "defense",
    "military": "defense",
    "housing": "real_estate",
    "real-estate": "real_estate",
    "property markets": "real_estate",
    "infrastructure": "construction",
    "cement": "construction",
    "transportation": "shipping",
    "transport": "shipping",
    "lng trade": "shipping",
    "grain trade": "shipping",
    "shipping disruption": "shipping",
    "container shipping": "shipping",
    "food service": "consumer_goods",
    "food processing": "consumer_goods",
    "luxury goods": "consumer_goods",
    "government finance": "government",
    "public finance": "government",
    "government services": "government",
    "sovereign debt": "financial",
    "fixed income": "financial",
    "emerging market debt": "financial",
    "nuclear energy": "energy",
    "hydropower": "energy",
    "electricity generation": "energy",
    "electricity": "energy",
    "natural gas": "energy",
    "agricultural commodities": "agriculture",
    "food security": "agriculture",
    "commodity markets": "commodities",
    "industrial equipment": "manufacturing",
    "heavy industry": "manufacturing",
    # Meta-terms that are NOT real sectors — map to None so they are silently dropped
    "trade": None,
    "labor markets": None,
    "households": None,
    "all sectors": None,
    "all": None,
    "energy hardest hit": None,
}

# GEDS engine node set — for event_to_graph_mapping
GEDS_NODES = {
    "TWN:semiconductors", "TWN:electronics", "TWN:shipping",
    "USA:semiconductors", "USA:automotive", "USA:electronics",
    "USA:aerospace", "USA:consumer_goods", "USA:shipping",
    "CHN:semiconductors", "CHN:automotive", "CHN:electronics", "CHN:consumer_goods",
    "JPN:automotive", "JPN:electronics", "JPN:semiconductors",
    "DEU:automotive", "DEU:electronics",
    "KOR:electronics", "KOR:semiconductors",
    "NLD:aerospace", "NLD:semiconductors",
    "VNM:electronics",
    "MYS:electronics", "MYS:semiconductors",
    "THA:automotive", "THA:electronics",
    "IND:electronics", "IND:consumer_goods",
    "MEX:automotive", "MEX:electronics",
    "CP:TaiwanStrait", "CP:Malacca", "CP:Suez", "CP:Hormuz",
}


# ── parsing helpers ────────────────────────────────────────────────────────

def normalize_country(name: str) -> str | None:
    """ISO3 lookup. Returns None if unknown (caller decides how to handle)."""
    if not name:
        return None
    k = name.strip().lower().rstrip(".").rstrip(",")
    # Strip parentheticals
    k = re.sub(r"\s*\([^)]*\)", "", k).strip()
    return COUNTRY_TO_ISO3.get(k)


def parse_country_list(raw: str) -> tuple[list[str], list[str], list[str], str]:
    """Returns (iso3_list, unmapped_names_list, expanded_regions, scope).

    scope ∈ {"country", "regional", "global"} — flag for downstream code.
    Region tokens like "EU"/"Eurozone" are expanded to representative ISO3
    members; the original term goes into `expanded_regions` for traceability.
    """
    if not raw:
        return [], [], [], "country"
    # Strip parentheticals
    raw = re.sub(r"\s*\([^)]*\)", "", raw)
    parts = re.split(r"[,;]|\sand\s|/", raw)
    iso: list[str] = []
    unmapped: list[str] = []
    expanded: list[str] = []
    scope = "country"
    for p in parts:
        p = p.strip()
        if not p:
            continue
        key = p.lower().rstrip(".").rstrip(",")
        if key in SCOPE_GLOBAL_TERMS:
            if scope != "regional":
                scope = "global"
            expanded.append(p)
            continue
        if key in REGION_TO_ISO3:
            for code in REGION_TO_ISO3[key]:
                if code not in iso:
                    iso.append(code)
            expanded.append(p)
            scope = "regional"
            continue
        code = normalize_country(p)
        if code:
            if code not in iso:
                iso.append(code)
        else:
            unmapped.append(p)
    return iso, unmapped, expanded, scope


def parse_sectors(raw: str) -> tuple[list[str], list[str]]:
    """Returns (taxonomy_sectors, unmapped_terms).
    Terms mapped to None in SECTOR_TAXONOMY are treated as filtered meta-terms
    (e.g. "all", "trade", "households") and are not counted as unmapped.
    """
    if not raw:
        return [], []
    raw = re.sub(r"\s*\([^)]*\)", "", raw)
    parts = re.split(r"[,;]|\sand\s|/", raw)
    out: list[str] = []
    unmapped: list[str] = []
    for p in parts:
        p = p.strip().lower()
        if not p:
            continue
        if p in SECTOR_TAXONOMY:
            sector = SECTOR_TAXONOMY[p]
            if sector and sector not in out:
                out.append(sector)
            # explicit None → meta-term, silently dropped
        else:
            unmapped.append(p)
    return out, unmapped


_NUM_RE = re.compile(
    r"(?P<sign>[−\-+])?\s*(?P<num>\d+(?:\.\d+)?)\s*(?:[–\-to]+\s*(?P<num2>\d+(?:\.\d+)?))?\s*(?P<pct>%|pp\b|percentage points)?",
    re.IGNORECASE,
)
# A token that looks like a year range "2003-2008" embedded in prose.
_YEAR_RANGE_RE = re.compile(r"\b(19|20)\d{2}\s*-\s*(19|20)?\d{2,4}\b")
_YEAR_RE = re.compile(r"\b(19|20)\d{2}\b")


def _is_year_match(m: re.Match) -> bool:
    """True when a numeric match looks like a year or year-range (not a percent)."""
    a = float(m.group("num"))
    b = m.group("num2")
    # Both numbers integer-valued AND in 1900-2100 → year(s)
    def _yearish(x: float) -> bool:
        return x == int(x) and 1900 <= x <= 2100
    if b is not None:
        return _yearish(a) and _yearish(float(b))
    return _yearish(a)


_INDEX_NAMES_RE = re.compile(
    r"\b(?:S&P|SP|FTSE|Nasdaq|Dow|DAX|Nikkei|Hang\s*Seng|CAC|STOXX|"
    r"BVSP|RTSI|KOSPI|TSX|ASX|MOEX|TTF)\s*\d+", re.IGNORECASE,
)


def parse_percent(raw: str) -> tuple[float | None, str]:
    """Strict parse of a percent value from prose.

    Strategy: only accept a numeric whose match group includes %, pp, or
    "percentage points". This avoids the entire class of bugs where:
      - "$275 billion" was being read as 275
      - "S&P 500" was being read as 500
      - "Nikkei 225 fell ~20%" was being read as 225 instead of 20
      - Year-range midpoints (2003-2008 → 2005.5) were being read as percent
    Returns (value, note). Notes flag ranges, currency-only text, etc.
    """
    if not raw or raw.strip().lower() in {"n/a", "na", "none", "—", "-"}:
        return None, "missing"
    s = raw.replace("–", "-").replace("—", "-").replace("−", "-")
    # Strip year tokens so they can't be picked up.
    s_clean = _YEAR_RANGE_RE.sub(" ", s)
    s_clean = re.sub(r"\b(19|20)\d{2}\b(?!\s*%)", " ", s_clean)
    # Strip stock-index names like "S&P 500", "Nikkei 225", "FTSE 100".
    s_clean = _INDEX_NAMES_RE.sub(" ", s_clean)
    has_pct_anywhere = "%" in s or "pp" in s.lower() or "percentage point" in s.lower()
    has_currency = bool(re.search(r"[$€£]\s*[\d.,]+", s))
    # Pass 1 (strict): require unit attached to the match.
    for m in _NUM_RE.finditer(s_clean):
        if _is_year_match(m):
            continue
        if not m.group("pct"):
            continue
        sign = -1.0 if m.group("sign") == "-" else 1.0
        a = float(m.group("num"))
        b = m.group("num2")
        if b:
            a = (a + float(b)) / 2.0
            note = "range_midpoint"
        else:
            note = "ok"
        return sign * a, note
    # No unit-attached number found. Be honest: don't fabricate a percent value
    # from prose with numbers in physical units (mb/d, bcm, $B, index levels…).
    # The audit will surface what the source said.
    if has_currency and not has_pct_anywhere:
        return None, "currency_only_no_pct"
    if not has_pct_anywhere:
        return None, "no_pct_unit_in_source"
    return None, "no_numeric_found"


def parse_year_range(raw: str) -> tuple[int | None, int | None]:
    """'2000–01' -> (2000, 2001), '2020–21' -> (2020, 2021), '2022–ongoing' -> (2022, None)."""
    if not raw:
        return None, None
    s = raw.replace("–", "-").replace("—", "-")
    m = re.search(r"(\d{4})(?:\s*-\s*(\d{2,4}|present|ongoing))?", s, re.IGNORECASE)
    if not m:
        return None, None
    y1 = int(m.group(1))
    y2_raw = m.group(2)
    if not y2_raw:
        return y1, y1
    if y2_raw.lower() in {"present", "ongoing"}:
        return y1, None
    y2 = int(y2_raw)
    if y2 < 100:
        y2 = (y1 // 100) * 100 + y2
    return y1, y2


_DUR_MONTHS_RE = re.compile(r"~?\s*(\d+)\+?\s*month", re.IGNORECASE)
_DUR_YEARS_RE = re.compile(r"~?\s*(\d+(?:\.\d+)?)\+?\s*year", re.IGNORECASE)
_DUR_WEEKS_RE = re.compile(r"~?\s*(\d+)\+?\s*week", re.IGNORECASE)
_DUR_DAYS_RE = re.compile(r"~?\s*(\d+)\+?\s*day", re.IGNORECASE)
_DUR_YEAR_RANGE_RE = re.compile(r"\b(19|20)(\d{2})\s*-\s*(19|20)?(\d{2,4})\b")


def parse_duration_months(raw: str) -> int | None:
    if not raw:
        return None
    s = raw.replace("–", "-").replace("—", "-")
    if m := _DUR_MONTHS_RE.search(s):
        return int(m.group(1))
    if m := _DUR_YEARS_RE.search(s):
        return int(round(float(m.group(1)) * 12))
    if m := _DUR_WEEKS_RE.search(s):
        return max(1, int(round(int(m.group(1)) / 4.345)))
    if m := _DUR_DAYS_RE.search(s):
        return max(0, int(round(int(m.group(1)) / 30.44)))
    # Fallback: year range like "2010-2015" or "2003-2008"
    if m := _DUR_YEAR_RANGE_RE.search(s):
        y1 = int(m.group(1) + m.group(2))
        end_century = m.group(3) or m.group(1)
        y2_part = m.group(4)
        y2 = int(end_century + y2_part) if len(y2_part) <= 2 else int(y2_part)
        if y2 < y1:
            y2 = (y1 // 100) * 100 + y2
        return max(1, (y2 - y1) * 12)
    return None


_RECOVERY_RE = re.compile(
    r"(?:recovery|reconstruction|rebuild(?:ing)?)\s*[:\-]?\s*(\d+(?:\.\d+)?)\+?\s*(month|year|week|day)",
    re.IGNORECASE,
)


def parse_recovery_months(raw: str) -> int | None:
    """Only return a value when the text explicitly says 'recovery: N years' or similar.
    The docx has no separate Recovery Time field; this scans Duration text for explicit
    recovery/reconstruction phrasing. Returning None means 'not stated' (audit-honest).
    """
    if not raw:
        return None
    s = raw.replace("–", "-").replace("—", "-")
    m = _RECOVERY_RE.search(s)
    if not m:
        return None
    num = float(m.group(1))
    unit = m.group(2).lower()
    if unit == "month":
        return int(num)
    if unit == "year":
        return int(round(num * 12))
    if unit == "week":
        return max(1, int(round(num / 4.345)))
    if unit == "day":
        return max(0, int(round(num / 30.44)))
    return None


def parse_confidence(raw: str) -> int | None:
    if not raw:
        return None
    m = re.search(r"\b([1-5])\b", raw)
    return int(m.group(1)) if m else None


# Canonical primary types — keep this list short. Anything not matched falls back
# to the first slash-separated token from the source.
_TYPE_NORMALIZATION = {
    "financial crisis": "Financial Crisis",
    "pandemic": "Pandemic",
    "natural disaster": "Natural Disaster",
    "energy crisis": "Energy Crisis",
    "trade war": "Trade War",
    "sanctions": "Sanctions",
    "war": "War",
    "semiconductor crisis": "Semiconductor Crisis",
    "shipping disruption": "Shipping Disruption",
    "port disruption": "Shipping Disruption",
    "geopolitical": "Geopolitical",
    "geopolitical disruption": "Geopolitical",
}


def normalize_event_type(raw: str) -> tuple[str, list[str]]:
    """Return (primary_type, secondary_types).

    Source uses combos like 'War / Sanctions (Geopolitical Disruption)'.
    Primary = first slash-separated token, normalised against the small set
    above when possible. Secondary = remaining tokens (also normalised).
    """
    if not raw:
        return "", []
    # Strip parentheticals
    cleaned = re.sub(r"\s*\([^)]*\)", "", raw).strip()
    parts = [p.strip() for p in re.split(r"[/]", cleaned) if p.strip()]
    if not parts:
        return "", []
    def _norm(t: str) -> str:
        return _TYPE_NORMALIZATION.get(t.lower(), t)
    primary = _norm(parts[0])
    secondary = [_norm(p) for p in parts[1:]]
    return primary, secondary


# ── per-event parsers ──────────────────────────────────────────────────────

def parse_detail_table(table_rows: list[list[str]]) -> dict:
    """Parse a 16x2 Field|Value table."""
    out: dict[str, str] = {}
    for row in table_rows:
        if len(row) < 2:
            continue
        key, val = row[0].strip(), row[1].strip()
        if key.lower() == "field":
            continue
        out[key] = val
    return out


def parse_paragraph_event(text: str) -> dict:
    """Parse paragraph-only events 31-42 in 'Field: value | Field: value | ...' form.

    Event 42 has a trailing 'Data Quality & Limitations' postscript that must
    be stripped before splitting — it has no leading pipe and pollutes the
    last field (Source) with prose.
    """
    # Cut off any postscript after the recognised list of fields.
    for terminator in ("Data Quality & Limitations", "Recommended Citation"):
        idx = text.find(terminator)
        if idx > 0:
            text = text[:idx].strip()
            break
    out: dict[str, str] = {}
    parts = re.split(r"\s*\|\s*", text)
    for p in parts:
        p = p.strip()
        if ":" not in p:
            continue
        key, val = p.split(":", 1)
        out[key.strip()] = val.strip()
    return out


def extract_country_specific_metrics(text: str) -> list[tuple[str, str, float, str]]:
    """Find patterns like 'Greece -26%' or 'Russia GDP -3.7%' in free-text.
    Returns list of (country_iso3, metric_hint, value, note).
    """
    if not text:
        return []
    found = []
    s = text.replace("−", "-").replace("–", "-").replace("—", "-")
    # Pattern: <Country> [GDP] [<context>]? [-+]?<num>% [pp]?
    pat = re.compile(
        r"\b([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+)?)\b[^.;|]{0,40}?([-+]?\s*\d+(?:\.\d+)?)\s*(%|pp)",
    )
    for m in pat.finditer(s):
        country_name = m.group(1)
        iso = normalize_country(country_name)
        if not iso:
            continue
        try:
            val = float(m.group(2).replace(" ", ""))
        except ValueError:
            continue
        found.append((iso, "gdp_or_trade", val, "from_freetext"))
    return found


# ── main ───────────────────────────────────────────────────────────────────

def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]

    if not DUMP.exists():
        print(f"ERROR: {DUMP} not found. Run docx dump first.", file=sys.stderr)
        return 1

    raw = json.loads(DUMP.read_text(encoding="utf-8"))
    paragraphs: list[str] = raw["paragraphs"]
    tables: list[list[list[str]]] = raw["tables"]

    # Build (event_id -> source-data) map.
    events: dict[int, dict] = {}

    # Phase 1: 30 detail tables = events 1-30
    detail_tables = tables[:30]
    # Find event headings in paragraphs to pair with detail tables
    event_heading_re = re.compile(r"Event\s+(\d+)\s*[—–-]\s*(.+)")
    heading_names: dict[int, str] = {}
    for p in paragraphs:
        if m := event_heading_re.match(p.strip()):
            heading_names[int(m.group(1))] = m.group(2).strip()

    for i, tbl in enumerate(detail_tables, start=1):
        d = parse_detail_table(tbl)
        d["_event_id"] = i
        d["_name_from_heading"] = heading_names.get(i, "")
        d["_source"] = "detail_table"
        events[i] = d

    # Phase 2: paragraph-only events 31-42 (one paragraph per event of form
    # "Year: ... | Type: ... | Affected: ... | ...")
    in_event = None
    buffer: list[str] = []
    para_events: dict[int, str] = {}
    for p in paragraphs:
        if m := event_heading_re.match(p.strip()):
            # flush previous
            if in_event and in_event >= 31:
                para_events[in_event] = " ".join(buffer).strip()
            in_event = int(m.group(1))
            buffer = []
        elif in_event and p.strip():
            buffer.append(p.strip())
    if in_event and in_event >= 31:
        para_events[in_event] = " ".join(buffer).strip()

    for eid, txt in para_events.items():
        d = parse_paragraph_event(txt)
        d["_event_id"] = eid
        d["_name_from_heading"] = heading_names.get(eid, "")
        d["_source"] = "paragraph"
        d["_raw_paragraph"] = txt
        events[eid] = d

    # ── Build the 3 CSVs + audit ─────────────────────────────────────────

    audit_lines: list[str] = []
    summary_lines: list[str] = []

    # 1. historical_events_expanded.csv
    expanded_path = CSV_DIR / "historical_events_expanded.csv"
    fields = [
        "event_id", "event_name", "year_start", "year_end",
        "event_type", "event_type_secondary",
        "affected_countries", "affected_regions", "scope",
        "affected_sectors", "trigger", "duration_months",
        "gdp_impact_percent", "trade_impact_percent", "inflation_impact_percent",
        "market_impact_percent", "recovery_time_months",
        "is_scenario", "confidence", "source",
    ]
    rows_expanded = []
    parse_notes: dict[int, list[str]] = defaultdict(list)
    unmapped_country_names: Counter = Counter()
    unmapped_sector_names: Counter = Counter()

    for eid in sorted(events):
        d = events[eid]

        def g(*keys: str) -> str:
            for k in keys:
                # case-insensitive key match
                for actual in d:
                    if actual.lower() == k.lower():
                        return d[actual]
            return ""

        name = g("Event Name") or d.get("_name_from_heading", "") or f"Event {eid}"
        year_raw = g("Year")
        y1, y2 = parse_year_range(year_raw)
        ev_type_raw = g("Event Type", "Type")
        ev_type_primary, ev_type_secondary = normalize_event_type(ev_type_raw)
        countries_raw = g("Affected Countries", "Affected")
        iso_list, unmapped_c, expanded_regions, scope = parse_country_list(countries_raw)
        if unmapped_c:
            unmapped_country_names.update(unmapped_c)
            parse_notes[eid].append(f"unmapped countries: {unmapped_c}")
        if expanded_regions:
            parse_notes[eid].append(f"expanded aggregate region terms: {expanded_regions}")
        sectors_raw = g("Affected Sectors", "Sectors")
        sectors_list, unmapped_s = parse_sectors(sectors_raw)
        if unmapped_s:
            unmapped_sector_names.update(unmapped_s)
            parse_notes[eid].append(f"unmapped sectors: {unmapped_s}")
        trigger = g("Trigger")
        duration_raw = g("Duration")
        duration_m = parse_duration_months(duration_raw)
        if duration_raw and duration_m is None:
            parse_notes[eid].append(f"duration not parseable: {duration_raw!r}")

        # Some paragraph events use "GDP Impact (Scenario)" instead of "GDP Impact (%)".
        gdp_raw = g("GDP Impact (%)", "GDP Impact", "GDP Impact (Scenario)")
        gdp_v, gdp_note = parse_percent(gdp_raw)
        if gdp_note not in ("ok", "missing"):
            parse_notes[eid].append(f"gdp[{gdp_note}]: {gdp_raw!r}")
        trade_raw = g("Trade Impact (%)", "Trade Impact")
        trade_v, trade_note = parse_percent(trade_raw)
        if trade_note not in ("ok", "missing"):
            parse_notes[eid].append(f"trade[{trade_note}]: {trade_raw!r}")
        infl_raw = g("Inflation Impact")
        infl_v, infl_note = parse_percent(infl_raw)
        if infl_note not in ("ok", "missing"):
            parse_notes[eid].append(f"infl[{infl_note}]: {infl_raw!r}")
        market_raw = g("Market Impact")
        market_v, market_note = parse_percent(market_raw)
        if market_note not in ("ok", "missing"):
            parse_notes[eid].append(f"market[{market_note}]: {market_raw!r}")
        # Source has no explicit Recovery Time field. Scan Duration for
        # "recovery: N years" or "reconstruction: N years" phrasing only.
        recovery_m = parse_recovery_months(duration_raw)
        conf_raw = g("Confidence Score", "Confidence")
        conf = parse_confidence(conf_raw)
        source = g("Primary Sources", "Source", "Sources")

        # Scenario detection — explicit markers from the source.
        is_scenario = bool(
            "scenario" in ev_type_raw.lower()
            or "scenario" in conf_raw.lower()
            or "scenario" in name.lower()
            or "(scenario" in countries_raw.lower()
            or any("scenario" in str(d.get(k, "")).lower() for k in d if "gdp" in k.lower())
        )

        rows_expanded.append({
            "event_id": eid,
            "event_name": name,
            "year_start": y1 if y1 else "",
            "year_end": y2 if y2 else "",
            "event_type": ev_type_primary,
            "event_type_secondary": ";".join(ev_type_secondary),
            "affected_countries": ";".join(iso_list),
            "affected_regions": ";".join(expanded_regions),
            "scope": scope,
            "affected_sectors": ";".join(sectors_list),
            "trigger": trigger,
            "duration_months": duration_m if duration_m is not None else "",
            "gdp_impact_percent": f"{gdp_v:.3f}" if gdp_v is not None else "",
            "trade_impact_percent": f"{trade_v:.3f}" if trade_v is not None else "",
            "inflation_impact_percent": f"{infl_v:.3f}" if infl_v is not None else "",
            "market_impact_percent": f"{market_v:.3f}" if market_v is not None else "",
            "recovery_time_months": recovery_m if recovery_m is not None else "",
            "is_scenario": "true" if is_scenario else "false",
            "confidence": conf if conf is not None else "",
            "source": source[:500],
        })

    with expanded_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows_expanded)
    print(f"wrote {expanded_path} ({len(rows_expanded)} rows)")

    # 2. validation_targets.csv (per-country breakdown extracted from freetext)
    val_path = CSV_DIR / "validation_targets.csv"
    val_fields = [
        "event_id", "country", "sector",
        "observed_gdp_change", "observed_trade_change",
        "observed_inflation_change", "observed_recovery_time", "source",
    ]
    val_rows = []
    for eid in sorted(events):
        d = events[eid]
        # Use country-specific metrics from GDP Impact / Trade Impact fields
        gdp_field = ""
        trade_field = ""
        for k in d:
            kl = k.lower()
            if "gdp impact" in kl:
                gdp_field = d[k]
            elif "trade impact" in kl:
                trade_field = d[k]
        for iso, _, val, note in extract_country_specific_metrics(gdp_field):
            val_rows.append({
                "event_id": eid, "country": iso, "sector": "",
                "observed_gdp_change": f"{val:.3f}",
                "observed_trade_change": "",
                "observed_inflation_change": "",
                "observed_recovery_time": "",
                "source": f"docx event {eid} GDP Impact field ({note})",
            })
        for iso, _, val, note in extract_country_specific_metrics(trade_field):
            val_rows.append({
                "event_id": eid, "country": iso, "sector": "",
                "observed_gdp_change": "",
                "observed_trade_change": f"{val:.3f}",
                "observed_inflation_change": "",
                "observed_recovery_time": "",
                "source": f"docx event {eid} Trade Impact field ({note})",
            })
        # If no country-specific metrics found, emit one row per affected country
        # with aggregate event-level values (so downstream models always have
        # something to join on).
        if not any(r["event_id"] == eid for r in val_rows):
            agg = next(r for r in rows_expanded if r["event_id"] == eid)
            countries = agg["affected_countries"].split(";") if agg["affected_countries"] else []
            for iso in countries[:5]:  # cap to avoid noise for global events
                val_rows.append({
                    "event_id": eid, "country": iso, "sector": "",
                    "observed_gdp_change": agg["gdp_impact_percent"],
                    "observed_trade_change": agg["trade_impact_percent"],
                    "observed_inflation_change": agg["inflation_impact_percent"],
                    "observed_recovery_time": agg["recovery_time_months"],
                    "source": f"docx event {eid} aggregate (no country-specific values in source)",
                })

    with val_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=val_fields)
        w.writeheader()
        w.writerows(val_rows)
    print(f"wrote {val_path} ({len(val_rows)} rows)")

    # 3. event_to_graph_mapping.csv
    map_path = CSV_DIR / "event_to_graph_mapping.csv"
    map_fields = ["event_id", "event_name", "country", "sector", "geds_node_id", "node_in_graph"]
    map_rows = []
    chokepoint_hints = {
        "Suez": "CP:Suez", "suez": "CP:Suez",
        "Malacca": "CP:Malacca", "malacca": "CP:Malacca",
        "Hormuz": "CP:Hormuz", "hormuz": "CP:Hormuz",
        "Taiwan Strait": "CP:TaiwanStrait", "taiwan strait": "CP:TaiwanStrait",
        "Panama Canal": None,  # not in graph
        "Red Sea": None,
        "Bosphorus": None,
    }
    for row in rows_expanded:
        eid = row["event_id"]
        countries = row["affected_countries"].split(";") if row["affected_countries"] else []
        sectors = row["affected_sectors"].split(";") if row["affected_sectors"] else []
        trigger = next(e for e in rows_expanded if e["event_id"] == eid)["trigger"]
        emitted = False
        # Cross product country × sector
        for c in countries:
            for s in sectors:
                node_id = f"{c}:{s}"
                map_rows.append({
                    "event_id": eid, "event_name": row["event_name"],
                    "country": c, "sector": s,
                    "geds_node_id": node_id,
                    "node_in_graph": node_id in GEDS_NODES,
                })
                emitted = True
            # Country-only row when no sector available
            if not sectors:
                map_rows.append({
                    "event_id": eid, "event_name": row["event_name"],
                    "country": c, "sector": "",
                    "geds_node_id": "",
                    "node_in_graph": False,
                })
                emitted = True
        # Chokepoint detection from trigger text
        for hint, cp_node in chokepoint_hints.items():
            if hint in trigger and cp_node:
                map_rows.append({
                    "event_id": eid, "event_name": row["event_name"],
                    "country": "", "sector": "chokepoint",
                    "geds_node_id": cp_node,
                    "node_in_graph": cp_node in GEDS_NODES,
                })
        if not emitted:
            map_rows.append({
                "event_id": eid, "event_name": row["event_name"],
                "country": "", "sector": "", "geds_node_id": "",
                "node_in_graph": False,
            })

    with map_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=map_fields)
        w.writeheader()
        w.writerows(map_rows)
    print(f"wrote {map_path} ({len(map_rows)} rows)")

    # 4. DATA_AUDIT.md
    audit_path = DOCS_DIR / "DATA_AUDIT.md"
    in_graph_count = sum(1 for r in map_rows if r["node_in_graph"])
    out_graph_count = sum(1 for r in map_rows if not r["node_in_graph"] and r["geds_node_id"])
    scenario_events = [r for r in rows_expanded if r["is_scenario"] == "true"]
    low_conf_events = [r for r in rows_expanded if r["confidence"] and int(r["confidence"]) <= 2]
    no_year_events = [r for r in rows_expanded if not r["year_start"]]
    no_country_events = [r for r in rows_expanded if not r["affected_countries"]]
    no_sector_events = [r for r in rows_expanded if not r["affected_sectors"]]
    no_gdp_events = [r for r in rows_expanded if not r["gdp_impact_percent"]]
    no_trade_events = [r for r in rows_expanded if not r["trade_impact_percent"]]
    no_recovery_events = [r for r in rows_expanded if not r["recovery_time_months"]]

    # Duplicates: same event_name
    name_counts = Counter(r["event_name"] for r in rows_expanded)
    duplicates = [n for n, c in name_counts.items() if c > 1]

    # Cross-references (Event 37 says "See Event 24")
    cross_refs = []
    for r in rows_expanded:
        if "see event" in r["event_name"].lower() or "see event" in r["trigger"].lower():
            cross_refs.append(r["event_id"])

    # Overlapping events (same year range)
    overlap_pairs = []
    for i, a in enumerate(rows_expanded):
        if not a["year_start"]:
            continue
        for b in rows_expanded[i+1:]:
            if not b["year_start"]:
                continue
            a_start, a_end = int(a["year_start"]), int(a["year_end"]) if a["year_end"] else int(a["year_start"])
            b_start, b_end = int(b["year_start"]), int(b["year_end"]) if b["year_end"] else int(b["year_start"])
            if a_start <= b_end and b_start <= a_end:
                # same year overlap
                if a_start == b_start or a_end == b_end:
                    overlap_pairs.append((a["event_id"], b["event_id"], a["event_name"], b["event_name"]))

    audit_md = [
        "# GEDS Historical Events — Data Audit",
        "",
        f"Generated from `backend/data/csv/historical_events_expanded.csv` "
        f"({len(rows_expanded)} events).",
        "",
        "Source document: `D:/GEDS-Historical-Economic-Disruption-Dataset-2000-2026.docx`",
        "Extracted via: `backend/scripts/extract_events_from_docx.py`",
        "",
        "## Missing-value counts",
        "",
        "| Field | Missing |",
        "|---|---|",
        f"| year_start | {len(no_year_events)} |",
        f"| affected_countries | {len(no_country_events)} |",
        f"| affected_sectors | {len(no_sector_events)} |",
        f"| gdp_impact_percent | {len(no_gdp_events)} |",
        f"| trade_impact_percent | {len(no_trade_events)} |",
        f"| recovery_time_months | {len(no_recovery_events)} |",
        "",
        "## Graph coverage",
        "",
        f"- Event-derived rows mapped to a node IN the current GEDS graph: **{in_graph_count}**",
        f"- Event-derived rows whose (country, sector) is NOT in the current GEDS graph: **{out_graph_count}**",
        "",
        "## Duplicates",
        "",
        f"Events sharing an identical name: **{len(duplicates)}**",
    ]
    for d in duplicates:
        audit_md.append(f"- `{d}`")
    if not duplicates:
        audit_md.append("- (none)")

    audit_md += [
        "",
        "## Cross-reference events (no own data, point to another)",
        "",
    ]
    if cross_refs:
        for cid in cross_refs:
            ev = next(r for r in rows_expanded if r["event_id"] == cid)
            audit_md.append(f"- Event {cid}: `{ev['event_name']}`")
    else:
        audit_md.append("- (none detected via heuristic)")

    audit_md += [
        "",
        "## Low-confidence events (confidence ≤ 2)",
        "",
    ]
    if low_conf_events:
        for r in low_conf_events:
            audit_md.append(f"- Event {r['event_id']} (`{r['event_name']}`) — confidence={r['confidence']}")
    else:
        audit_md.append("- (none)")

    audit_md += [
        "",
        "## Scenario / forward-looking events (not historical observations)",
        "",
    ]
    if scenario_events:
        for r in scenario_events:
            audit_md.append(f"- Event {r['event_id']} (`{r['event_name']}`)")
    else:
        audit_md.append("- (none detected via heuristic — manual review recommended for events ≥ 41)")

    audit_md += [
        "",
        "## Overlapping time windows",
        "",
        f"Pairs of events whose year ranges intersect: **{len(overlap_pairs)}**",
        "(showing only same-start or same-end overlaps to limit noise)",
        "",
    ]
    for a, b, na, nb in overlap_pairs[:25]:
        audit_md.append(f"- Event {a} (`{na[:40]}`) overlaps Event {b} (`{nb[:40]}`)")
    if len(overlap_pairs) > 25:
        audit_md.append(f"- ... and {len(overlap_pairs) - 25} more")

    audit_md += [
        "",
        "## Unmapped country names encountered",
        "",
    ]
    if unmapped_country_names:
        for name, c in unmapped_country_names.most_common():
            audit_md.append(f"- `{name}` ({c}×)")
    else:
        audit_md.append("- (all countries mapped to ISO3)")

    audit_md += [
        "",
        "## Unmapped sector terms encountered",
        "",
    ]
    if unmapped_sector_names:
        for name, c in unmapped_sector_names.most_common():
            audit_md.append(f"- `{name}` ({c}×)")
    else:
        audit_md.append("- (all sectors mapped to taxonomy)")

    audit_md += [
        "",
        "## Per-event parse notes (rounding, missing units, etc.)",
        "",
    ]
    for eid in sorted(parse_notes):
        for note in parse_notes[eid]:
            audit_md.append(f"- Event {eid}: {note}")
    if not parse_notes:
        audit_md.append("- (no parsing anomalies)")

    audit_path.write_text("\n".join(audit_md), encoding="utf-8")
    print(f"wrote {audit_path}")

    # 5. DATA_SUMMARY.md
    summary_path = DOCS_DIR / "DATA_SUMMARY.md"
    type_counter = Counter(r["event_type"] for r in rows_expanded if r["event_type"])
    year_counter: Counter = Counter()
    for r in rows_expanded:
        if r["year_start"]:
            year_counter[r["year_start"]] += 1
    conf_counter: Counter = Counter()
    for r in rows_expanded:
        if r["confidence"]:
            conf_counter[r["confidence"]] += 1
    all_countries: set[str] = set()
    for r in rows_expanded:
        for c in (r["affected_countries"] or "").split(";"):
            if c:
                all_countries.add(c)
    all_sectors: set[str] = set()
    for r in rows_expanded:
        for s in (r["affected_sectors"] or "").split(";"):
            if s:
                all_sectors.add(s)
    missing_table = [
        ("event_type", sum(1 for r in rows_expanded if not r["event_type"])),
        ("affected_countries", len(no_country_events)),
        ("affected_sectors", len(no_sector_events)),
        ("duration_months", sum(1 for r in rows_expanded if not r["duration_months"])),
        ("gdp_impact_percent", len(no_gdp_events)),
        ("trade_impact_percent", len(no_trade_events)),
        ("inflation_impact_percent", sum(1 for r in rows_expanded if not r["inflation_impact_percent"])),
        ("market_impact_percent", sum(1 for r in rows_expanded if not r["market_impact_percent"])),
        ("recovery_time_months", len(no_recovery_events)),
        ("confidence", sum(1 for r in rows_expanded if not r["confidence"])),
    ]

    summary_md = [
        "# GEDS Historical Events — Summary Statistics",
        "",
        f"Total events: **{len(rows_expanded)}**",
        "",
        "## Events by type",
        "",
        "| Type | Count |",
        "|---|---|",
    ]
    for t, c in type_counter.most_common():
        summary_md.append(f"| {t} | {c} |")

    summary_md += [
        "",
        "## Events by start year",
        "",
        "| Year | Count |",
        "|---|---|",
    ]
    for y in sorted(year_counter):
        summary_md.append(f"| {y} | {year_counter[y]} |")

    summary_md += [
        "",
        "## Confidence distribution",
        "",
        "| Confidence | Count |",
        "|---|---|",
    ]
    for c in sorted(conf_counter):
        summary_md.append(f"| {c} | {conf_counter[c]} |")

    summary_md += [
        "",
        f"## Countries covered: {len(all_countries)}",
        "",
        ", ".join(f"`{c}`" for c in sorted(all_countries)),
        "",
        f"## Sectors covered (taxonomy): {len(all_sectors)}",
        "",
        ", ".join(f"`{s}`" for s in sorted(all_sectors)),
        "",
        "## Scope distribution",
        "",
        "| Scope | Count |",
        "|---|---|",
    ]
    scope_counter: Counter = Counter(r["scope"] for r in rows_expanded)
    for sc, c in scope_counter.most_common():
        summary_md.append(f"| {sc} | {c} |")
    summary_md += [
        "",
        f"Scenario / forward-looking events: **{sum(1 for r in rows_expanded if r['is_scenario'] == 'true')}**",
        "",
        "## Missing-data statistics",
        "",
        "| Field | Missing | % Missing | Note |",
        "|---|---|---|---|",
    ]
    n = len(rows_expanded)
    notes_for_field = {
        "recovery_time_months": (
            "source docx has no explicit Recovery Time field; values present "
            "only when text says e.g. 'reconstruction: 10 years'"
        ),
        "duration_months": "filled from Duration field or year-range fallback",
        "inflation_impact_percent": "many events have qualitative-only inflation text",
        "trade_impact_percent": "financial-crisis events rarely disaggregate trade",
        "market_impact_percent": "some events lack equity-market figures",
        "affected_countries": "blank when source says only 'Global' (see scope column)",
        "affected_sectors": "blank when source says 'all sectors' (meta-term filtered)",
    }
    for fld, count in missing_table:
        pct = (count / n * 100) if n else 0
        note = notes_for_field.get(fld, "")
        summary_md.append(f"| {fld} | {count} | {pct:.1f}% | {note} |")

    summary_path.write_text("\n".join(summary_md), encoding="utf-8")
    print(f"wrote {summary_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
