"""Integrate the bootstrapped scientific-layer CSVs into the engine.

Phases 1-9 per user spec. Strict rules:
  - DO NOT overwrite calibrated engine values (calibration_v2.json wins).
  - DO NOT silently modify engine behavior. Wiring is via metadata + registry
    helpers; the propagation math is untouched.
  - Preserve NULL throughout.
  - Mark uncertainty explicitly via mechanism_validation labels.

Outputs:
  backend/app/data/scientific_registry.py     (Phase 1)
  backend/data/calibration/literature_priors.json     (Phase 4)
  backend/data/csv/benchmark_event_matrix_v3.csv      (Phase 6)
  backend/data/calibration/benchmark_v3.json          (Phase 7)
  docs/PUBLICATION_READINESS_V2.md                    (Phase 8)
  docs/FINAL_STATE.md                                 (Phase 9)

Phases 2 and 3 are "wiring" — the engine code is not edited; instead the
registry exposes lookups (`get_country_sector_presence`, `get_chokepoint`) that
downstream code (and future engine refactors) can use. Phase 2 specifically
makes the existing heuristic country×sector map data-driven (loaded from CSV
rather than hardcoded) while preserving the same values.
"""

from __future__ import annotations

import csv
import json
import sys
import time
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO / "backend"))
sys.path.insert(0, str(REPO / "backend" / "scripts"))

CSV_DIR = REPO / "backend" / "data" / "csv"
CALIB_DIR = REPO / "backend" / "data" / "calibration"
DOCS = REPO / "docs"
DATA_PY_DIR = REPO / "backend" / "app" / "data"


# ── PHASE 1: scientific_registry.py ──────────────────────────────────────

PHASE1_MODULE_BODY = '''"""GEDS scientific evidence registry — frozen dataclasses for the bootstrapped
scientific-layer CSVs. Single read-only source-of-truth, loaded at import time.

CSVs (all in backend/data/csv/, each row has a `_source_origin` column):
  - country_sector_presence.csv  → CountrySector
  - propagation_literature.csv   → PropagationPaper
  - financial_contagion.csv      → FinancialContagion
  - global_chokepoints.csv       → Chokepoint
  - mechanism_validation.csv     → MechanismEvidence

This module does NOT modify engine behavior. Downstream code can consume the
registry to label outputs, surface citations, or filter benchmarks.

Generated by `backend/scripts/integrate_scientific_layer.py`. Re-run that
script after the CSVs change.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

_CSV_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "csv"


def _f(s) -> float | None:
    if s in (None, "", "—"):
        return None
    try:
        return float(s)
    except (ValueError, TypeError):
        return None


def _i(s) -> int | None:
    v = _f(s)
    return int(v) if v is not None else None


def _load(name: str) -> list[dict]:
    p = _CSV_DIR / name
    if not p.exists():
        return []
    with p.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


@dataclass(frozen=True)
class CountrySector:
    country_iso3: str
    sector: str
    present: bool
    source_origin: str


@dataclass(frozen=True)
class PropagationPaper:
    paper_id: str
    title: str
    authors: str
    year: int | None
    journal: str
    doi: str
    mechanism: str
    key_quantitative_finding: str
    propagation_multiplier_estimate: float | None
    recovery_duration_estimate_months: int | None
    evidence_confidence: str
    source_origin: str


@dataclass(frozen=True)
class FinancialContagion:
    paper_id: str
    title: str
    authors: str
    year: int | None
    journal: str
    doi: str
    contagion_type: str
    key_finding: str
    spillover_coefficient_estimate: float | None
    scope: str
    evidence_confidence: str
    source_origin: str


@dataclass(frozen=True)
class Chokepoint:
    chokepoint_id: str
    name: str
    capacity_share_global_trade_pct: float | None
    capacity_share_global_seaborne_oil_pct: float | None
    capacity_share_global_seaborne_trade_pct: float | None
    tsmc_foundry_share_pct: float | None
    tsmc_advanced_chips_share_pct: float | None
    expected_annual_loss_usd_b: float | None
    rerouting_cost_per_day_usd_b: float | None
    failure_duration_observed_days: float | None
    failure_event_year: int | None
    failure_event_name: str
    downstream_sectors: tuple[str, ...]
    evidence_citation: str
    doi_or_url: str
    evidence_confidence: str
    source_origin: str


@dataclass(frozen=True)
class MechanismEvidence:
    mechanism: str
    label: str                      # SUPPORTED / UNCERTAIN / UNSUPPORTED
    evidence_strength: str          # STRONG / MODERATE / WEAK / ABSENT
    key_paper: str
    geds_assumption_used: str
    matches_evidence: str
    confidence: int | None
    source_origin: str


# ── load all CSVs ──────────────────────────────────────────────────────────

def _load_country_sectors() -> tuple[tuple[CountrySector, ...], dict[str, set[str]]]:
    rows = _load("country_sector_presence.csv")
    out = []
    by_country: dict[str, set[str]] = {}
    for r in rows:
        cs = CountrySector(
            country_iso3=r.get("country_iso3", ""),
            sector=r.get("sector", ""),
            present=r.get("present", "false").lower() == "true",
            source_origin=r.get("_source_origin", ""),
        )
        out.append(cs)
        if cs.present:
            by_country.setdefault(cs.country_iso3, set()).add(cs.sector)
    return tuple(out), by_country


def _load_propagation_papers() -> tuple[tuple[PropagationPaper, ...], dict[str, list[PropagationPaper]]]:
    rows = _load("propagation_literature.csv")
    out = []
    by_mech: dict[str, list[PropagationPaper]] = {}
    for r in rows:
        p = PropagationPaper(
            paper_id=r.get("paper_id", ""),
            title=r.get("title", ""),
            authors=r.get("authors", ""),
            year=_i(r.get("year")),
            journal=r.get("journal", ""),
            doi=r.get("doi", ""),
            mechanism=r.get("mechanism", ""),
            key_quantitative_finding=r.get("key_quantitative_finding", ""),
            propagation_multiplier_estimate=_f(r.get("propagation_multiplier_estimate")),
            recovery_duration_estimate_months=_i(r.get("recovery_duration_estimate_months")),
            evidence_confidence=r.get("evidence_confidence", ""),
            source_origin=r.get("_source_origin", ""),
        )
        out.append(p)
        by_mech.setdefault(p.mechanism, []).append(p)
    return tuple(out), by_mech


def _load_financial() -> tuple[tuple[FinancialContagion, ...], dict[str, FinancialContagion]]:
    rows = _load("financial_contagion.csv")
    out = []
    for r in rows:
        out.append(FinancialContagion(
            paper_id=r.get("paper_id", ""),
            title=r.get("title", ""),
            authors=r.get("authors", ""),
            year=_i(r.get("year")),
            journal=r.get("journal", ""),
            doi=r.get("doi", ""),
            contagion_type=r.get("contagion_type", ""),
            key_finding=r.get("key_finding", ""),
            spillover_coefficient_estimate=_f(r.get("spillover_coefficient_estimate")),
            scope=r.get("scope", ""),
            evidence_confidence=r.get("evidence_confidence", ""),
            source_origin=r.get("_source_origin", ""),
        ))
    by_id = {x.paper_id: x for x in out}
    return tuple(out), by_id


def _load_chokepoints() -> tuple[tuple[Chokepoint, ...], dict[str, Chokepoint]]:
    rows = _load("global_chokepoints.csv")
    out = []
    for r in rows:
        out.append(Chokepoint(
            chokepoint_id=r.get("chokepoint_id", ""),
            name=r.get("name", ""),
            capacity_share_global_trade_pct=_f(r.get("capacity_share_global_trade_pct")),
            capacity_share_global_seaborne_oil_pct=_f(r.get("capacity_share_global_seaborne_oil_pct")),
            capacity_share_global_seaborne_trade_pct=_f(r.get("capacity_share_global_seaborne_trade_pct")),
            tsmc_foundry_share_pct=_f(r.get("tsmc_foundry_share_pct")),
            tsmc_advanced_chips_share_pct=_f(r.get("tsmc_advanced_chips_share_pct")),
            expected_annual_loss_usd_b=_f(r.get("expected_annual_loss_usd_b")),
            rerouting_cost_per_day_usd_b=_f(r.get("rerouting_cost_per_day_usd_b")),
            failure_duration_observed_days=_f(r.get("failure_duration_observed_days")),
            failure_event_year=_i(r.get("failure_event_year")),
            failure_event_name=r.get("failure_event_name", ""),
            downstream_sectors=tuple(s.strip() for s in r.get("downstream_sectors", "").split(";") if s.strip()),
            evidence_citation=r.get("evidence_citation", ""),
            doi_or_url=r.get("doi_or_url", ""),
            evidence_confidence=r.get("evidence_confidence", ""),
            source_origin=r.get("_source_origin", ""),
        ))
    by_id = {x.chokepoint_id: x for x in out}
    return tuple(out), by_id


def _load_mechanism() -> tuple[tuple[MechanismEvidence, ...], dict[str, MechanismEvidence]]:
    rows = _load("mechanism_validation.csv")
    out = []
    for r in rows:
        out.append(MechanismEvidence(
            mechanism=r.get("mechanism", ""),
            label=r.get("label", ""),
            evidence_strength=r.get("evidence_strength", ""),
            key_paper=r.get("key_paper", ""),
            geds_assumption_used=r.get("geds_assumption_used", ""),
            matches_evidence=r.get("matches_evidence", ""),
            confidence=_i(r.get("confidence")),
            source_origin=r.get("_source_origin", ""),
        ))
    return tuple(out), {x.mechanism: x for x in out}


# Module-level loaded data
COUNTRY_SECTORS, _COUNTRY_TO_SECTORS = _load_country_sectors()
PROPAGATION_PAPERS, _PAPERS_BY_MECH = _load_propagation_papers()
FINANCIAL, _FINANCIAL_BY_ID = _load_financial()
CHOKEPOINTS, _CHOKEPOINT_BY_ID = _load_chokepoints()
MECHANISMS, _MECH_BY_NAME = _load_mechanism()


# ── lookup helpers ────────────────────────────────────────────────────────


def country_has_sector(iso3: str, sector: str) -> bool | None:
    """Phase 2 contract: NEVER invent. Returns None if the (country, sector)
    pair is not in the CSV (UNKNOWN per user spec).
    """
    sectors = _COUNTRY_TO_SECTORS.get(iso3)
    if sectors is None:
        return None  # UNKNOWN — country not in registry
    return sector in sectors


def get_country_present_sectors(iso3: str) -> tuple[str, ...] | None:
    sectors = _COUNTRY_TO_SECTORS.get(iso3)
    return tuple(sorted(sectors)) if sectors is not None else None


def get_propagation_papers(mechanism: str) -> tuple[PropagationPaper, ...]:
    return tuple(_PAPERS_BY_MECH.get(mechanism, ()))


def get_chokepoint(chokepoint_id: str) -> Chokepoint | None:
    return _CHOKEPOINT_BY_ID.get(chokepoint_id)


def get_mechanism_evidence(mechanism: str) -> MechanismEvidence | None:
    return _MECH_BY_NAME.get(mechanism)


def supported_mechanisms() -> tuple[MechanismEvidence, ...]:
    return tuple(m for m in MECHANISMS if m.label == "SUPPORTED")


def unsupported_mechanisms() -> tuple[MechanismEvidence, ...]:
    return tuple(m for m in MECHANISMS if m.label == "UNSUPPORTED")


def uncertain_mechanisms() -> tuple[MechanismEvidence, ...]:
    return tuple(m for m in MECHANISMS if m.label == "UNCERTAIN")


__all__ = [
    "CountrySector", "PropagationPaper", "FinancialContagion",
    "Chokepoint", "MechanismEvidence",
    "COUNTRY_SECTORS", "PROPAGATION_PAPERS", "FINANCIAL",
    "CHOKEPOINTS", "MECHANISMS",
    "country_has_sector", "get_country_present_sectors",
    "get_propagation_papers", "get_chokepoint",
    "get_mechanism_evidence",
    "supported_mechanisms", "unsupported_mechanisms", "uncertain_mechanisms",
]
'''


def phase1_write_registry() -> Path:
    p = DATA_PY_DIR / "scientific_registry.py"
    p.write_text(PHASE1_MODULE_BODY, encoding="utf-8")
    print(f"Phase 1: wrote {p}")
    return p


# ── PHASE 4: literature_priors.json (does NOT overwrite calibration) ─────

def phase4_write_literature_priors() -> Path:
    """Aggregate the propagation_literature.csv quantitative estimates into a
    priors JSON. The engine does not consume this file — it's documentation
    plus a future-calibration anchor. calibration_v2.json best_params remain
    the active engine config."""
    papers = []
    with (CSV_DIR / "propagation_literature.csv").open(encoding="utf-8", newline="") as f:
        papers = list(csv.DictReader(f))

    # Collect numeric estimates per mechanism
    priors: dict[str, dict] = {}
    for p in papers:
        mech = p["mechanism"]
        priors.setdefault(mech, {"papers": [], "estimates": {}})
        priors[mech]["papers"].append({
            "paper_id": p["paper_id"],
            "doi": p["doi"],
            "key_finding": p["key_quantitative_finding"],
            "evidence_confidence": p["evidence_confidence"],
        })
        try:
            mult = float(p.get("propagation_multiplier_estimate") or "")
            priors[mech]["estimates"].setdefault("propagation_multiplier", []).append(mult)
        except ValueError:
            pass
        try:
            rec = int(float(p.get("recovery_duration_estimate_months") or ""))
            priors[mech]["estimates"].setdefault("recovery_duration_months", []).append(rec)
        except ValueError:
            pass

    # Summarize to point estimates + ranges
    summary = {}
    for mech, data in priors.items():
        s = {
            "n_papers": len(data["papers"]),
            "papers": data["papers"],
            "estimates": {},
        }
        for est_name, vals in data["estimates"].items():
            s["estimates"][est_name] = {
                "values": vals,
                "mean": float(np.mean(vals)) if vals else None,
                "min": float(min(vals)) if vals else None,
                "max": float(max(vals)) if vals else None,
            }
        summary[mech] = s

    out = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "source": "backend/data/csv/propagation_literature.csv",
        "note": (
            "Literature-derived priors. NOT used to overwrite calibrated engine "
            "values per user constraint 'Do not overwrite manually calibrated "
            "values'. The engine continues to use calibration_v2.json best_params. "
            "Use these priors only for: (a) bounding parameter ranges in future "
            "calibration runs, (b) sensitivity analysis sanity checks, "
            "(c) publication-defence sources."
        ),
        "priors_by_mechanism": summary,
        "current_engine_config": "loaded from backend/data/calibration/calibration_v2.json (unchanged)",
    }
    p = CALIB_DIR / "literature_priors.json"
    p.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Phase 4: wrote {p}")
    return p


# ── PHASE 6: benchmark_event_matrix_v3.csv ───────────────────────────────

def phase6_event_matrix_v3() -> tuple[Path, dict]:
    """Re-emit benchmark_event_matrix_v3.csv from benchmark_event_matrix_v2 +
    missing_event_mapping. Honest about what gained/changed.
    """
    v2 = []
    with (CSV_DIR / "benchmark_event_matrix_v2.csv").open(encoding="utf-8", newline="") as f:
        v2 = list(csv.DictReader(f))
    missing = []
    with (CSV_DIR / "missing_event_mapping.csv").open(encoding="utf-8", newline="") as f:
        missing = list(csv.DictReader(f))
    missing_by_eid = {int(r["event_id"]): r for r in missing if r["event_id"].isdigit()}

    rows = []
    n_ok_v2 = 0
    n_ok_v3 = 0
    for r in v2:
        try:
            eid = int(r["event_id"])
        except (ValueError, KeyError):
            continue
        status = r.get("mapping_status", "")
        if status == "OK":
            n_ok_v2 += 1
            n_ok_v3 += 1
        gap = missing_by_eid.get(eid, {}).get("gap_description", "")
        suggested = missing_by_eid.get(eid, {}).get("suggested_resolution", "")
        rows.append({
            "event_id": r["event_id"],
            "event_name": r["event_name"],
            "sectors_source": r.get("sectors_source", ""),
            "sectors_mapped": r.get("sectors_mapped", ""),
            "countries": r.get("countries", ""),
            "mapped_graph_nodes": r.get("mapped_graph_nodes", ""),
            "n_mapped_nodes": r.get("n_mapped_nodes", ""),
            "target_gdp": r.get("target_gdp", ""),
            "confidence": r.get("confidence", ""),
            "has_peer_review": r.get("has_peer_review", ""),
            "mapping_status_v2": status,
            "mapping_status_v3": status,  # unchanged — no new evidence available
            "gap_description": gap,
            "suggested_resolution": suggested,
            "v3_change_note": (
                "no change — no new evidence ingested this phase; gain requires "
                "real OECD ICIO / WIOD data or extended Industry enum"
            ),
        })

    p = CSV_DIR / "benchmark_event_matrix_v3.csv"
    fields = list(rows[0].keys())
    with p.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)
    print(f"Phase 6: wrote {p}; N_OK v2={n_ok_v2}, v3={n_ok_v3}")
    return p, {"n_before": n_ok_v2, "n_after": n_ok_v3,
               "n_gap_documented": len([m for m in missing if m["current_mapping_status"] != "OK"])}


# ── PHASE 7: benchmark_v3.json with 95% bootstrap CIs ────────────────────

def phase7_benchmark_v3() -> Path:
    """Re-run benchmark on the v2-expanded graph (already built) using the
    same EngineConfig — calibrated_v2 best params. Adds 95% bootstrap CIs.
    """
    # Use the same machinery from phase_expanded_validation.py
    from app.core.backtest import backtest_event
    from app.core.baselines import leontief_predict, linear_diffusion_predict
    from app.core.graph import compile_graph
    from app.core.types import EngineConfig, Industry, ShockSpec
    # Build/install v2 expanded graph
    from phase_expanded_validation import (
        build_expanded_v2_nodes, build_expanded_v2_edges,
        install_expanded_v2_graph, remap_events, write_expanded_v2,
    )
    nodes = build_expanded_v2_nodes()
    edges = build_expanded_v2_edges(nodes)
    install_expanded_v2_graph(nodes, edges)
    from app.data.seed import load_graph
    snap = load_graph()
    graph = compile_graph(snap)

    # Load calibrated config
    cal_path = CALIB_DIR / "calibration_v2.json"
    if cal_path.exists():
        data = json.loads(cal_path.read_text(encoding="utf-8"))
        best = data.get("best_params", {})
        cfg = EngineConfig(**{k: v for k, v in best.items() if k in EngineConfig.model_fields})
    else:
        cfg = EngineConfig()

    remapped = remap_events(nodes)
    eligible = [r for r in remapped if r["mapping_status"] == "OK"]
    n = len(eligible)
    pred_seirs = np.zeros(n); pred_leon = np.zeros(n); pred_diff = np.zeros(n); obs = np.zeros(n)
    per_event = []
    t0 = time.time()
    for i, r in enumerate(eligible):
        ev = r["_translated"]
        bt = backtest_event(ev, graph, cfg)
        pred_seirs[i] = bt.industry_loss_predicted
        obs[i] = bt.industry_loss_observed
        try:
            industry = Industry(ev["observed"]["most_impacted_industry"])
            shocks = [ShockSpec(**s) for s in ev["shocks"]]
            pred_leon[i] = leontief_predict(graph, shocks, industry, ev["horizon_weeks"]).industry_loss
            pred_diff[i] = linear_diffusion_predict(graph, shocks, industry, ev["horizon_weeks"]).industry_loss
        except Exception as exc:
            print(f"  baseline failed event_id={r['event_id']}: {exc}")
        per_event.append({"event_id": r["event_id"], "name": r["event_name"],
                          "target": float(obs[i]), "seirs": float(pred_seirs[i]),
                          "leontief": float(pred_leon[i]), "linear_diffusion": float(pred_diff[i])})
    pred_naive = np.full_like(obs, obs.mean()) if n > 0 else np.zeros(0)

    # Metrics + 95% bootstrap CIs
    def _r2(pred, obs):
        ss_res = float(((obs - pred) ** 2).sum())
        ss_tot = float(((obs - obs.mean()) ** 2).sum())
        return 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan")

    def _pearson(a, b):
        if a.size < 2 or np.std(a) == 0 or np.std(b) == 0:
            return float("nan")
        da, db = a - a.mean(), b - b.mean()
        d = float(np.sqrt((da @ da) * (db @ db)))
        return float(da @ db / d) if d > 0 else float("nan")

    def _mape(pred, obs):
        mask = obs != 0
        if mask.sum() == 0: return float("nan")
        return float(np.abs((pred[mask] - obs[mask]) / obs[mask]).mean()) * 100

    def _bootstrap(pred, obs, fn, n_boot=1000):
        if pred.size < 2:
            return (float("nan"), float("nan"))
        rng = np.random.default_rng(42)
        samples = []
        for _ in range(n_boot):
            idx = rng.integers(0, pred.size, size=pred.size)
            samples.append(fn(pred[idx], obs[idx]))
        return float(np.percentile(samples, 2.5)), float(np.percentile(samples, 97.5))

    def _score(name, pred, obs):
        if pred.size == 0:
            return {"model": name, "n_events": 0}
        mae = float(np.abs(pred - obs).mean())
        rmse = float(np.sqrt(((pred - obs) ** 2).mean()))
        r2 = _r2(pred, obs)
        pearson = _pearson(pred, obs)
        mape = _mape(pred, obs)
        mae_lo, mae_hi = _bootstrap(pred, obs, lambda p, o: float(np.abs(p - o).mean()))
        rmse_lo, rmse_hi = _bootstrap(pred, obs, lambda p, o: float(np.sqrt(((p - o) ** 2).mean())))
        r2_lo, r2_hi = _bootstrap(pred, obs, _r2)
        pear_lo, pear_hi = _bootstrap(pred, obs, _pearson)
        return {
            "model": name, "n_events": int(obs.size),
            "mae": round(mae, 5), "mae_ci95": [round(mae_lo, 5), round(mae_hi, 5)],
            "rmse": round(rmse, 5), "rmse_ci95": [round(rmse_lo, 5), round(rmse_hi, 5)],
            "r_squared": round(r2, 4), "r_squared_ci95": [round(r2_lo, 4), round(r2_hi, 4)],
            "pearson": round(pearson, 4), "pearson_ci95": [round(pear_lo, 4), round(pear_hi, 4)],
            "mape_pct": round(mape, 2),
        }

    scores = [
        _score("SEIRS-Bullwhip-Hysteresis (GEDS)", pred_seirs, obs),
        _score("Leontief", pred_leon, obs),
        _score("Linear Diffusion", pred_diff, obs),
        _score("Naive Persistence", pred_naive, obs),
    ]
    elapsed = time.time() - t0

    out = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "graph_nodes": len(snap.nodes),
        "graph_edges": len(snap.edges),
        "engine_config_source": "calibration_v2.json best_params (unchanged)",
        "engine_config": cfg.model_dump(),
        "n_events_corpus": 42,
        "n_events_benchmarked": n,
        "models": scores,
        "per_event": per_event,
        "elapsed_seconds": round(elapsed, 1),
        "comparison_vs_v2": (
            "v3 benchmark uses identical graph + config + eligible-event set as "
            "v2-expanded. Numerical results should match v2 exactly (this run is "
            "a re-emission, not a re-calibration). Adds 95% bootstrap CIs."
        ),
    }
    p = CALIB_DIR / "benchmark_v3.json"
    p.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Phase 7: wrote {p}")
    for s in scores:
        print(f"  {s['model']}: MAE={s['mae']} CI={s.get('mae_ci95')}, R²={s.get('r_squared')} CI={s.get('r_squared_ci95')}")
    return p


# ── PHASE 8: PUBLICATION_READINESS_V2.md ────────────────────────────────

def phase8_publication_readiness(coverage: dict) -> Path:
    """Drive entirely from mechanism_validation.csv labels."""
    rows = []
    with (CSV_DIR / "mechanism_validation.csv").open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    supported = [r for r in rows if r["label"] == "SUPPORTED"]
    uncertain = [r for r in rows if r["label"] == "UNCERTAIN"]
    unsupported = [r for r in rows if r["label"] == "UNSUPPORTED"]

    p = DOCS / "PUBLICATION_READINESS_V2.md"
    lines = [
        "# GEDS Publication Readiness v2",
        "",
        f"Generated: `{datetime.now(timezone.utc).isoformat()}`",
        "Drives entirely from `mechanism_validation.csv` which was bootstrapped from",
        "`docs/publication_risk_report.md` §6 (Evidence Confidence Register).",
        "",
        "## Validated components (SUPPORTED)",
        "",
        "These mechanisms have published peer-reviewed support AND a GEDS implementation:",
        "",
        "| Mechanism | Evidence strength | Key paper | GEDS assumption | Matches evidence? | Confidence |",
        "|---|---|---|---|---|---|",
    ]
    for r in supported:
        lines.append(
            f"| {r['mechanism']} | {r['evidence_strength']} | {r['key_paper']} | "
            f"{r['geds_assumption_used'][:80]} | {r['matches_evidence']} | {r['confidence']} / 5 |"
        )

    lines += [
        "",
        "## Heuristic components (UNCERTAIN — needs evidence anchor)",
        "",
        "| Mechanism | Evidence strength | Key paper | GEDS assumption | Status |",
        "|---|---|---|---|---|",
    ]
    for r in uncertain:
        lines.append(
            f"| {r['mechanism']} | {r['evidence_strength']} | {r['key_paper']} | "
            f"{r['geds_assumption_used'][:80]} | {r['matches_evidence']} |"
        )

    lines += [
        "",
        "## Unsupported assumptions (UNSUPPORTED — must be addressed before publication)",
        "",
        "| Mechanism | Evidence strength | Key paper | GEDS assumption | Risk |",
        "|---|---|---|---|---|",
    ]
    for r in unsupported:
        lines.append(
            f"| {r['mechanism']} | {r['evidence_strength']} | {r['key_paper']} | "
            f"{r['geds_assumption_used'][:80]} | {r['matches_evidence']} |"
        )

    lines += [
        "",
        "## Remaining risks (from publication_risk_report.md §1)",
        "",
        "These risks were flagged in the original audit and remain unaddressed in",
        "the current integration pass (no engine values were changed):",
        "",
        "1. **CRITICAL — Negative R² on structural models**: GEDS R² = −0.566 on N=23. "
        "Diagnosis (per audit §1): heuristic edge weights; OECD ICIO not yet ingested.",
        "2. **HIGH — SEIRS re-susceptibility rate (ξ) is arbitrary**: no empirical "
        "calibration found in the literature. Either set ξ=0 (plain SEIR) or run "
        "sensitivity analysis with explicit uncertainty bands.",
        "3. **HIGH — Country×sector presence is heuristic**: bootstrapped from "
        "GEDS's own SPECIALTY_PRESENCE map; OECD ICIO 2018 / WIOD 2016 ingestion "
        "is the only real fix.",
        "4. **HIGH — Finance sector parameters not from ECB/BIS**: ECB WP1666 "
        "bilateral coefficients and IMF Ch.21 logit parameters are publicly "
        "available but not yet wired into the engine.",
        "",
        "## Honest assessment of this integration pass",
        "",
        "- **Scientific registry built** ✓ — all 5 dataclasses load and expose lookups.",
        "- **Mechanism labels published** ✓ — SUPPORTED / UNCERTAIN / UNSUPPORTED per source.",
        "- **Engine values NOT changed** ✓ — calibrated_v2 params remain authoritative.",
        "- **Literature priors documented** ✓ in `calibration_v2/literature_priors.json`.",
        "- **No new events gained** — `benchmark_event_matrix_v3.csv` is identical "
        "to v2 in OK-status counts (still 23). Gaining events requires OECD ICIO "
        "ingestion or further engine enum extensions, both of which are real-data "
        "work not done in this pass.",
        "- **Bootstrapped CSVs are flagged** — every row in the 6 new CSVs carries "
        "a `_source_origin` column. Where the source did not provide a numeric "
        "value, the cell is NULL (empty). No values were invented.",
        "",
        f"**Counts:** SUPPORTED: {len(supported)}, UNCERTAIN: {len(uncertain)}, "
        f"UNSUPPORTED: {len(unsupported)}.",
        "",
        "## Status verdict",
        "",
        "GEDS is **publication-defensible for the SUPPORTED mechanisms** "
        "(supply-chain propagation, bullwhip amplification, hysteresis, chokepoint "
        "risk) provided that:",
        "",
        "1. The UNSUPPORTED items above are explicitly disclosed in any paper / ISEF "
        "presentation, not hidden.",
        "2. The negative R² is reported with its causal diagnosis (heuristic edge "
        "weights), not as a model-quality claim.",
        "3. The 'SEIRS-Bullwhip-Hysteresis' brand is qualified — the prior forensics "
        "showed those layers are partially active on the expanded graph but the "
        "weight of model effect remains in network propagation + amplification.",
        "",
    ]
    p.write_text("\n".join(lines), encoding="utf-8")
    print(f"Phase 8: wrote {p}")
    return p


# ── PHASE 9: FINAL_STATE.md ───────────────────────────────────────────────

def phase9_final_state(bench_v3_path: Path) -> Path:
    """Headline numbers from all artifacts in the repo. Honest, no spin."""
    # Counts
    def _count_csv(name):
        try:
            with (CSV_DIR / name).open(encoding="utf-8", newline="") as f:
                return sum(1 for _ in csv.DictReader(f))
        except FileNotFoundError:
            return None

    n_nodes = _count_csv("expanded_graph_nodes_v2.csv")
    n_edges = _count_csv("expanded_graph_edges_v2.csv")
    n_events = _count_csv("master_event_registry.csv")
    n_papers = _count_csv("papers_catalog.csv")
    n_lit = _count_csv("literature_catalog.csv")
    n_datasets = _count_csv("master_dataset_registry.csv")
    n_evidence = _count_csv("event_evidence_registry.csv")
    n_prop_papers = _count_csv("propagation_literature.csv")
    n_choke = _count_csv("global_chokepoints.csv")
    n_mech = _count_csv("mechanism_validation.csv")
    n_country_sector = _count_csv("country_sector_presence.csv")
    n_missing = _count_csv("missing_event_mapping.csv")

    bench = json.loads(bench_v3_path.read_text(encoding="utf-8"))
    seirs = next(m for m in bench["models"] if m["model"].startswith("SEIRS"))
    diff = next(m for m in bench["models"] if m["model"] == "Linear Diffusion")
    leon = next(m for m in bench["models"] if m["model"] == "Leontief")
    naive = next(m for m in bench["models"] if m["model"] == "Naive Persistence")

    # Sectors covered
    sectors = set()
    with (CSV_DIR / "country_sector_presence.csv").open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            if r["present"] == "true":
                sectors.add(r["sector"])

    p = DOCS / "FINAL_STATE.md"
    lines = [
        "# GEDS — Final State (after scientific-layer integration)",
        "",
        f"Snapshot: `{datetime.now(timezone.utc).isoformat()}`",
        "",
        "## Headline counts",
        "",
        f"- **Graph nodes:** {n_nodes} (`expanded_graph_nodes_v2.csv`)",
        f"- **Graph edges:** {n_edges} (`expanded_graph_edges_v2.csv`)",
        f"- **Sectors active in engine:** 19 (`Industry` enum) of which {len(sectors)} "
        f"are present in ≥1 country in `country_sector_presence.csv`",
        f"- **Events catalogued:** {n_events} (`master_event_registry.csv`)",
        f"- **Events benchmarkable:** {bench['n_events_benchmarked']} (engine sector + graph filter)",
        f"- **Peer-reviewed papers (catalog):** {n_papers}",
        f"- **Literature references (extended):** {n_lit}",
        f"- **Datasets catalogued:** {n_datasets}",
        f"- **Event-evidence rows:** {n_evidence} (peer-reviewed ingestion pass)",
        f"- **Propagation-mechanism papers (new):** {n_prop_papers}",
        f"- **Chokepoints (new):** {n_choke}",
        f"- **Mechanism validation rows:** {n_mech}",
        f"- **Country-sector presence rows:** {n_country_sector}",
        f"- **Missing-event-mapping rows (gap log):** {n_missing}",
        "",
        "## Benchmark v3 (engine + 95% bootstrap CIs)",
        "",
        "Same engine config as v2-expanded (calibrated_v2 DE-best params; not changed).",
        f"N = {bench['n_events_benchmarked']} events. {n_events - bench['n_events_benchmarked']} events excluded for sector/graph/target gaps.",
        "",
        "| Model | MAE | MAE 95% CI | R² | R² 95% CI | Pearson |",
        "|---|---|---|---|---|---|",
    ]
    for s in (seirs, leon, diff, naive):
        lines.append(
            f"| {s['model']} | {s['mae']} | "
            f"[{s.get('mae_ci95', [0, 0])[0]}, {s.get('mae_ci95', [0, 0])[1]}] | "
            f"{s.get('r_squared')} | "
            f"[{s.get('r_squared_ci95', ['NA', 'NA'])[0]}, {s.get('r_squared_ci95', ['NA', 'NA'])[1]}] | "
            f"{s.get('pearson')} |"
        )

    lines += [
        "",
        "## Remaining limitations (do NOT hide these)",
        "",
        "1. **Negative R²** for all structural models. Root cause per `publication_risk_report.md`: "
        "heuristic edge weights. OECD ICIO / WIOD ingestion is the documented fix.",
        "2. **Bootstrapped CSVs**: the 6 new scientific-layer CSVs were built from existing repo "
        "evidence (`publication_risk_report.md`, `papers_catalog.csv`, `expanded_graph_nodes_v2.csv`). "
        "Each row has a `_source_origin` column. Some cells are NULL where the source provided no value.",
        "3. **No new events benchmarkable** in this pass. v3 has the same 23 OK events as v2-expanded. "
        "Gaining events requires real OECD ICIO data or extended engine enum.",
        "4. **`country_sector_presence.csv` is circular** — derived from the same heuristic map "
        "that produced `expanded_graph_nodes_v2.csv`. Replacing the heuristic at source requires "
        "OECD ICIO 2018 ingestion.",
        "5. **`missing_event_mapping.csv` lists gaps, not new mappings**. 19 events remain "
        "UNMAPPED / NO_TARGET / SCENARIO.",
        "6. **2 mechanisms UNSUPPORTED** per `mechanism_validation.csv`: SEIRS re-susceptibility "
        "rate (ξ), country×sector heuristic weights.",
        "7. **3 mechanisms UNCERTAIN**: SEIRS supply-chain threshold, financial contagion "
        "extreme-value parameters, healthcare sector propagation.",
        "8. **4 mechanisms SUPPORTED**: supply-chain network propagation (Carvalho 2021 QJE), "
        "bullwhip amplification (Lee 1997), hysteresis (Cerra 2020), chokepoint systemic risk "
        "(Verschuur 2025 Nature Comms).",
        "",
        "## What changed in this pass",
        "",
        "- **Source files:** none (engine code unchanged).",
        "- **New module:** `backend/app/data/scientific_registry.py` exposes 5 frozen dataclasses + 9 lookup helpers.",
        "- **New CSVs:** 6 bootstrapped from existing evidence (every row provenanced).",
        "- **New JSONs:** `literature_priors.json` documents per-mechanism priors (engine not modified).",
        "- **New docs:** `PUBLICATION_READINESS_V2.md` reports SUPPORTED/UNCERTAIN/UNSUPPORTED labels.",
        "",
        "## Reproducibility",
        "",
        "```",
        "python backend/scripts/bootstrap_scientific_layer.py",
        "python backend/scripts/integrate_scientific_layer.py",
        "```",
        "",
        "Both scripts are deterministic given the same input CSVs and a fixed numpy seed (42).",
        "",
    ]
    p.write_text("\n".join(lines), encoding="utf-8")
    print(f"Phase 9: wrote {p}")
    return p


# ── main ────────────────────────────────────────────────────────────────

def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]

    print("Phase 1: scientific_registry.py...")
    phase1_write_registry()
    # Verify it imports
    import importlib
    import app.data.scientific_registry as sr
    importlib.reload(sr)
    print(f"  loads OK: {len(sr.MECHANISMS)} mechanisms, {len(sr.CHOKEPOINTS)} chokepoints, "
          f"{len(sr.PROPAGATION_PAPERS)} papers, {len(sr.COUNTRY_SECTORS)} country×sector rows")
    print()

    print("Phase 2: country_sector_presence wired via registry helpers (no engine code edit).")
    sample = sr.get_country_present_sectors("USA")
    print(f"  USA present sectors via registry: {len(sample) if sample else 0}")
    print()

    print("Phase 3: chokepoint metadata wired via registry helpers.")
    cp = sr.get_chokepoint("CP:TaiwanStrait")
    print(f"  CP:TaiwanStrait via registry: tsmc_foundry_share_pct={cp.tsmc_foundry_share_pct if cp else 'MISSING'}")
    print()

    print("Phase 4: literature priors (does NOT overwrite calibration)...")
    phase4_write_literature_priors()
    print()

    print("Phase 5: mechanism evidence — labels in mechanism_validation.csv.")
    sup = sr.supported_mechanisms()
    unc = sr.uncertain_mechanisms()
    uns = sr.unsupported_mechanisms()
    print(f"  SUPPORTED: {len(sup)}, UNCERTAIN: {len(unc)}, UNSUPPORTED: {len(uns)}")
    print()

    print("Phase 6: benchmark_event_matrix_v3.csv...")
    _, coverage = phase6_event_matrix_v3()
    print(f"  N_before (v2) = {coverage['n_before']}, N_after (v3) = {coverage['n_after']}")
    print()

    print("Phase 7: benchmark v3 with 95% bootstrap CIs...")
    bench_path = phase7_benchmark_v3()
    print()

    print("Phase 8: PUBLICATION_READINESS_V2.md...")
    phase8_publication_readiness(coverage)
    print()

    print("Phase 9: FINAL_STATE.md...")
    phase9_final_state(bench_path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
