"""GEDS data registry — single Python source of truth.

This module loads the 4 master CSV registries on import and exposes them as
dataclass-like records plus a small set of helper lookups. Other modules
should ONLY use this interface for read-only access to the catalogue layer.

Master CSVs:
  - backend/data/csv/master_event_registry.csv
  - backend/data/csv/master_dataset_registry.csv
  - backend/data/csv/master_model_registry.csv
  - backend/data/csv/master_literature_registry.csv

Generated by `backend/scripts/build_master_registries.py`. Do not edit by
hand — re-run the script after upstream CSVs change.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass, field
from pathlib import Path

_CSV_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "csv"

# ── GEDS taxonomy constants (kept in sync with extract_events_from_docx.py
#    and build_master_registries.py) ─────────────────────────────────────────

GEDS_SECTORS: frozenset[str] = frozenset({
    "semiconductors", "automotive", "electronics", "aerospace",
    "consumer_goods", "shipping", "energy", "agriculture",
    "financial", "real_estate", "construction", "manufacturing",
    "tourism", "healthcare", "chemicals", "metals", "technology",
    "telecommunications", "defense", "government", "commodities",
    "mining", "textiles",
})

GEDS_NODES: frozenset[str] = frozenset({
    "TWN:semiconductors", "TWN:electronics", "TWN:shipping",
    "USA:semiconductors", "USA:automotive", "USA:electronics",
    "USA:aerospace", "USA:consumer_goods", "USA:shipping",
    "CHN:semiconductors", "CHN:automotive", "CHN:electronics", "CHN:consumer_goods",
    "JPN:automotive", "JPN:electronics", "JPN:semiconductors",
    "DEU:automotive", "DEU:electronics",
    "KOR:electronics", "KOR:semiconductors",
    "NLD:aerospace", "NLD:semiconductors",
    "VNM:electronics",
    "MYS:electronics", "MYS:semiconductors",
    "THA:automotive", "THA:electronics",
    "IND:electronics", "IND:consumer_goods",
    "MEX:automotive", "MEX:electronics",
    "CP:TaiwanStrait", "CP:Malacca", "CP:Suez", "CP:Hormuz",
})


@dataclass(frozen=True)
class Event:
    """One historical event from master_event_registry.csv."""
    event_id: int
    event_name: str
    year_start: str
    year_end: str
    event_type: str
    event_type_secondary: str
    scope: str
    is_scenario: bool
    affected_countries_iso3: tuple[str, ...]
    affected_regions: str
    affected_sectors: tuple[str, ...]
    duration_months: int | None
    gdp_impact_percent: float | None
    trade_impact_percent: float | None
    inflation_impact_percent: float | None
    market_impact_percent: float | None
    recovery_time_months: int | None
    confidence: int | None
    graph_nodes_affected_in_geds: tuple[str, ...]
    shock_origin_nodes: tuple[str, ...]
    estimated_initial_shock_strength: float | None
    duration_weeks: int | None
    benchmark_actual_peak_impact: float | None
    benchmark_actual_total_loss: float | None
    benchmark_countries_affected_count: int | None
    validation_targets_v2_rows: int
    validation_targets_expanded_rows: int
    literature_papers_corroborating: tuple[str, ...]
    source: str


@dataclass(frozen=True)
class Dataset:
    """One external dataset from master_dataset_registry.csv."""
    dataset_id: str
    dataset_name: str
    provider: str
    category: str
    description: str
    coverage_start: str
    coverage_end: str
    update_frequency: str
    geographic_scope: str
    variables: str
    format: str
    api_available: str
    download_url: str
    limitations: str
    confidence: int | None
    priority: str
    priority_reason: str
    citation: str


@dataclass(frozen=True)
class Model:
    """One benchmark model from master_model_registry.csv."""
    model_id: str
    model_name: str
    category: str
    description: str
    inputs: str
    outputs: str
    advantages: str
    limitations: str
    computational_complexity: str
    interpretability_qualitative: str
    data_requirements: str
    implementation_difficulty: str
    score_prediction_accuracy: int | None
    score_interpretability: int | None
    score_scalability: int | None
    score_robustness: int | None
    score_runtime: int | None
    score_data_requirements: int | None
    score_research_support: int | None
    score_expected_geds_value: int | None
    evidence_source: str


@dataclass(frozen=True)
class LiteratureEntry:
    """One paper from master_literature_registry.csv."""
    registry_id: str
    title: str
    authors: str
    year: str
    journal: str
    doi: str
    citation_count: str
    research_area: str
    methodology: str
    dataset_used: str
    main_findings: str
    limitations: str
    geds_relevance_score: int | None
    confidence: int | None
    primary_source: str
    cross_ref: str


# ── load helpers ───────────────────────────────────────────────────────────


def _to_int(s: str) -> int | None:
    try:
        return int(float(s))
    except (ValueError, TypeError):
        return None


def _to_float(s: str) -> float | None:
    try:
        return float(s)
    except (ValueError, TypeError):
        return None


def _to_tuple(s: str, sep: str = ";") -> tuple[str, ...]:
    if not s or s.upper() == "UNCERTAIN":
        return ()
    return tuple(t.strip() for t in s.split(sep) if t.strip())


def _load_csv(name: str) -> list[dict]:
    p = _CSV_DIR / name
    if not p.exists():
        return []
    with p.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _load_events() -> tuple[tuple[Event, ...], dict[int, Event]]:
    rows = _load_csv("master_event_registry.csv")
    events: list[Event] = []
    for r in rows:
        try:
            eid = int(r["event_id"])
        except (ValueError, KeyError):
            continue
        events.append(Event(
            event_id=eid,
            event_name=r.get("event_name", ""),
            year_start=r.get("year_start", ""),
            year_end=r.get("year_end", ""),
            event_type=r.get("event_type", ""),
            event_type_secondary=r.get("event_type_secondary", ""),
            scope=r.get("scope", ""),
            is_scenario=r.get("is_scenario", "false").lower() == "true",
            affected_countries_iso3=_to_tuple(r.get("affected_countries_iso3", "")),
            affected_regions=r.get("affected_regions", ""),
            affected_sectors=_to_tuple(r.get("affected_sectors", "")),
            duration_months=_to_int(r.get("duration_months", "")),
            gdp_impact_percent=_to_float(r.get("gdp_impact_percent", "")),
            trade_impact_percent=_to_float(r.get("trade_impact_percent", "")),
            inflation_impact_percent=_to_float(r.get("inflation_impact_percent", "")),
            market_impact_percent=_to_float(r.get("market_impact_percent", "")),
            recovery_time_months=_to_int(r.get("recovery_time_months", "")),
            confidence=_to_int(r.get("confidence", "")),
            graph_nodes_affected_in_geds=_to_tuple(r.get("graph_nodes_affected_in_geds", "")),
            shock_origin_nodes=_to_tuple(r.get("shock_origin_nodes", "")),
            estimated_initial_shock_strength=_to_float(r.get("estimated_initial_shock_strength", "")),
            duration_weeks=_to_int(r.get("duration_weeks", "")),
            benchmark_actual_peak_impact=_to_float(r.get("benchmark_actual_peak_impact", "")),
            benchmark_actual_total_loss=_to_float(r.get("benchmark_actual_total_loss", "")),
            benchmark_countries_affected_count=_to_int(r.get("benchmark_countries_affected_count", "")),
            validation_targets_v2_rows=_to_int(r.get("validation_targets_v2_rows", "0")) or 0,
            validation_targets_expanded_rows=_to_int(r.get("validation_targets_expanded_rows", "0")) or 0,
            literature_papers_corroborating=_to_tuple(r.get("literature_papers_corroborating", "")),
            source=r.get("source", ""),
        ))
    return tuple(events), {e.event_id: e for e in events}


def _load_datasets() -> tuple[tuple[Dataset, ...], dict[str, Dataset]]:
    rows = _load_csv("master_dataset_registry.csv")
    out = []
    for r in rows:
        out.append(Dataset(
            dataset_id=r.get("dataset_id", ""),
            dataset_name=r.get("dataset_name", ""),
            provider=r.get("provider", ""),
            category=r.get("category", ""),
            description=r.get("description", ""),
            coverage_start=r.get("coverage_start", ""),
            coverage_end=r.get("coverage_end", ""),
            update_frequency=r.get("update_frequency", ""),
            geographic_scope=r.get("geographic_scope", ""),
            variables=r.get("variables", ""),
            format=r.get("format", ""),
            api_available=r.get("api_available", ""),
            download_url=r.get("download_url", ""),
            limitations=r.get("limitations", ""),
            confidence=_to_int(r.get("confidence", "")),
            priority=r.get("priority", ""),
            priority_reason=r.get("priority_reason", ""),
            citation=r.get("citation", ""),
        ))
    return tuple(out), {d.dataset_id: d for d in out}


def _load_models() -> tuple[tuple[Model, ...], dict[str, Model]]:
    rows = _load_csv("master_model_registry.csv")
    out = []
    for r in rows:
        out.append(Model(
            model_id=r.get("model_id", ""),
            model_name=r.get("model_name", ""),
            category=r.get("category", ""),
            description=r.get("description", ""),
            inputs=r.get("inputs", ""),
            outputs=r.get("outputs", ""),
            advantages=r.get("advantages", ""),
            limitations=r.get("limitations", ""),
            computational_complexity=r.get("computational_complexity", ""),
            interpretability_qualitative=r.get("interpretability_qualitative", ""),
            data_requirements=r.get("data_requirements", ""),
            implementation_difficulty=r.get("implementation_difficulty", ""),
            score_prediction_accuracy=_to_int(r.get("score_prediction_accuracy", "")),
            score_interpretability=_to_int(r.get("score_interpretability", "")),
            score_scalability=_to_int(r.get("score_scalability", "")),
            score_robustness=_to_int(r.get("score_robustness", "")),
            score_runtime=_to_int(r.get("score_runtime", "")),
            score_data_requirements=_to_int(r.get("score_data_requirements", "")),
            score_research_support=_to_int(r.get("score_research_support", "")),
            score_expected_geds_value=_to_int(r.get("score_expected_geds_value", "")),
            evidence_source=r.get("evidence_source", ""),
        ))
    return tuple(out), {m.model_id: m for m in out}


def _load_literature() -> tuple[tuple[LiteratureEntry, ...], dict[str, LiteratureEntry]]:
    rows = _load_csv("master_literature_registry.csv")
    out = []
    for r in rows:
        out.append(LiteratureEntry(
            registry_id=r.get("registry_id", ""),
            title=r.get("title", ""),
            authors=r.get("authors", ""),
            year=r.get("year", ""),
            journal=r.get("journal", ""),
            doi=r.get("doi", ""),
            citation_count=r.get("citation_count", ""),
            research_area=r.get("research_area", ""),
            methodology=r.get("methodology", ""),
            dataset_used=r.get("dataset_used", ""),
            main_findings=r.get("main_findings", ""),
            limitations=r.get("limitations", ""),
            geds_relevance_score=_to_int(r.get("geds_relevance_score", "")),
            confidence=_to_int(r.get("confidence", "")),
            primary_source=r.get("primary_source", ""),
            cross_ref=r.get("cross_ref", ""),
        ))
    return tuple(out), {x.registry_id: x for x in out}


# ── module-level catalogues (loaded once at import) ────────────────────────

EVENTS, _EVENT_BY_ID = _load_events()
DATASETS, _DATASET_BY_ID = _load_datasets()
MODELS, _MODEL_BY_ID = _load_models()
LITERATURE, _LIT_BY_ID = _load_literature()


# ── public lookup helpers ──────────────────────────────────────────────────


def get_event(event_id: int) -> Event | None:
    return _EVENT_BY_ID.get(event_id)


def get_dataset(dataset_id: str) -> Dataset | None:
    return _DATASET_BY_ID.get(dataset_id)


def get_model(model_id: str) -> Model | None:
    return _MODEL_BY_ID.get(model_id)


def get_literature(registry_id: str) -> LiteratureEntry | None:
    return _LIT_BY_ID.get(registry_id)


def events_by_country(iso3: str) -> tuple[Event, ...]:
    """All events that touch a given country (ISO3)."""
    iso3 = iso3.upper()
    return tuple(e for e in EVENTS if iso3 in e.affected_countries_iso3)


def events_by_sector(sector: str) -> tuple[Event, ...]:
    """All events that touch a given sector (must be a member of GEDS_SECTORS)."""
    return tuple(e for e in EVENTS if sector in e.affected_sectors)


def events_with_literature_corroboration() -> tuple[Event, ...]:
    """Events that ≥1 peer-reviewed paper in the literature catalogue measures."""
    return tuple(e for e in EVENTS if e.literature_papers_corroborating)


def high_priority_datasets() -> tuple[Dataset, ...]:
    return tuple(d for d in DATASETS if d.priority == "HIGH")


def models_by_category(category: str) -> tuple[Model, ...]:
    return tuple(m for m in MODELS if m.category == category)


def deeply_cataloged_literature() -> tuple[LiteratureEntry, ...]:
    """Literature entries with full author/year/DOI (from papers_catalog.csv)."""
    return tuple(x for x in LITERATURE if x.primary_source == "papers_catalog.csv")


__all__ = [
    "GEDS_SECTORS", "GEDS_NODES",
    "Event", "Dataset", "Model", "LiteratureEntry",
    "EVENTS", "DATASETS", "MODELS", "LITERATURE",
    "get_event", "get_dataset", "get_model", "get_literature",
    "events_by_country", "events_by_sector",
    "events_with_literature_corroboration",
    "high_priority_datasets", "models_by_category",
    "deeply_cataloged_literature",
]


# ── PEER-REVIEWED EVIDENCE LAYER ──
# Hand-curated peer-reviewed evidence registry (Phase 1 of evidence ingestion).
# Loaded from `event_evidence_registry.csv` at import time.

@dataclass(frozen=True)
class EventEvidence:
    """One row of peer-reviewed evidence linking a paper to an event."""
    event_id: int
    event_name: str
    paper_id: str
    paper_title: str
    doi: str
    source_type: str
    publication_year: int | None
    gdp_impact_pct: float | None
    trade_impact_pct: float | None
    inflation_impact_pct: float | None
    market_impact_pct: float | None
    recovery_duration_months: int | None
    affected_sectors: str
    affected_countries: str
    uncertainty_lower: float | None
    uncertainty_upper: float | None
    confidence_score: int
    notes: str


@dataclass(frozen=True)
class BenchmarkTarget:
    """One row of high-confidence benchmark target from `benchmark_targets_expanded.csv`."""
    event_id: int
    event_name: str
    target_gdp_loss: float | None
    target_trade_loss: float | None
    target_inflation_change: float | None
    target_market_loss: float | None
    uncertainty_band_lower: float | None
    uncertainty_band_upper: float | None
    target_duration_months: int | None
    source_paper: str


def _load_event_evidence() -> tuple[tuple["EventEvidence", ...], dict[int, list["EventEvidence"]]]:
    rows = _load_csv("event_evidence_registry.csv")
    out: list[EventEvidence] = []
    for r in rows:
        try:
            out.append(EventEvidence(
                event_id=int(r["event_id"]),
                event_name=r.get("event_name", ""),
                paper_id=r.get("paper_id", ""),
                paper_title=r.get("paper_title", ""),
                doi=r.get("doi", ""),
                source_type=r.get("source_type", ""),
                publication_year=_to_int(r.get("publication_year", "")),
                gdp_impact_pct=_to_float(r.get("gdp_impact_pct", "")),
                trade_impact_pct=_to_float(r.get("trade_impact_pct", "")),
                inflation_impact_pct=_to_float(r.get("inflation_impact_pct", "")),
                market_impact_pct=_to_float(r.get("market_impact_pct", "")),
                recovery_duration_months=_to_int(r.get("recovery_duration_months", "")),
                affected_sectors=r.get("affected_sectors", ""),
                affected_countries=r.get("affected_countries", ""),
                uncertainty_lower=_to_float(r.get("uncertainty_lower", "")),
                uncertainty_upper=_to_float(r.get("uncertainty_upper", "")),
                confidence_score=_to_int(r.get("confidence_score", "")) or 0,
                notes=r.get("notes", ""),
            ))
        except (ValueError, KeyError):
            continue
    by_event: dict[int, list[EventEvidence]] = {}
    for e in out:
        by_event.setdefault(e.event_id, []).append(e)
    return tuple(out), by_event


def _load_benchmark_targets() -> tuple[tuple["BenchmarkTarget", ...], dict[int, "BenchmarkTarget"]]:
    rows = _load_csv("benchmark_targets_expanded.csv")
    out: list[BenchmarkTarget] = []
    for r in rows:
        try:
            out.append(BenchmarkTarget(
                event_id=int(r["event_id"]),
                event_name=r.get("event_name", ""),
                target_gdp_loss=_to_float(r.get("target_gdp_loss", "")),
                target_trade_loss=_to_float(r.get("target_trade_loss", "")),
                target_inflation_change=_to_float(r.get("target_inflation_change", "")),
                target_market_loss=_to_float(r.get("target_market_loss", "")),
                uncertainty_band_lower=_to_float(r.get("uncertainty_band_lower", "")),
                uncertainty_band_upper=_to_float(r.get("uncertainty_band_upper", "")),
                target_duration_months=_to_int(r.get("target_duration_months", "")),
                source_paper=r.get("source_paper", ""),
            ))
        except (ValueError, KeyError):
            continue
    return tuple(out), {b.event_id: b for b in out}


EVENT_EVIDENCE, _EVIDENCE_BY_EVENT = _load_event_evidence()
BENCHMARK_TARGETS, _BENCHMARK_BY_EVENT = _load_benchmark_targets()


def get_event_evidence(event_id: int) -> tuple[EventEvidence, ...]:
    """All evidence rows for a specific event_id."""
    return tuple(_EVIDENCE_BY_EVENT.get(event_id, []))


def events_with_direct_support() -> tuple[Event, ...]:
    """Events backed by ≥1 paper with confidence ≥4 AND a quantitative GDP/trade/inflation value."""
    ids_with_support: set[int] = set()
    for ev_rows in _EVIDENCE_BY_EVENT.values():
        for r in ev_rows:
            if r.confidence_score >= 4 and (
                r.gdp_impact_pct is not None
                or r.trade_impact_pct is not None
                or r.inflation_impact_pct is not None
            ):
                ids_with_support.add(r.event_id)
                break
    return tuple(e for e in EVENTS if e.event_id in ids_with_support)


def high_confidence_events(min_avg_confidence: float = 4.0) -> tuple[Event, ...]:
    """Events whose evidence rows have mean confidence ≥ min_avg_confidence."""
    out: list[Event] = []
    for e in EVENTS:
        rows = _EVIDENCE_BY_EVENT.get(e.event_id, [])
        if not rows:
            continue
        avg = sum(r.confidence_score for r in rows) / len(rows)
        if avg >= min_avg_confidence:
            out.append(e)
    return tuple(out)


def benchmark_targets() -> tuple["BenchmarkTarget", ...]:
    """All benchmark targets (Phase 3 output)."""
    return BENCHMARK_TARGETS


__all__ += [
    "EventEvidence", "BenchmarkTarget",
    "EVENT_EVIDENCE", "BENCHMARK_TARGETS",
    "get_event_evidence", "events_with_direct_support",
    "high_confidence_events", "benchmark_targets",
]
