"""GEDS scientific evidence registry — frozen dataclasses for the bootstrapped
scientific-layer CSVs. Single read-only source-of-truth, loaded at import time.

CSVs (all in backend/data/csv/, each row has a `_source_origin` column):
  - country_sector_presence.csv  → CountrySector
  - propagation_literature.csv   → PropagationPaper
  - financial_contagion.csv      → FinancialContagion
  - global_chokepoints.csv       → Chokepoint
  - mechanism_validation.csv     → MechanismEvidence

This module does NOT modify engine behavior. Downstream code can consume the
registry to label outputs, surface citations, or filter benchmarks.

Generated by `backend/scripts/integrate_scientific_layer.py`. Re-run that
script after the CSVs change.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

_CSV_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "csv"


def _f(s) -> float | None:
    if s in (None, "", "—"):
        return None
    try:
        return float(s)
    except (ValueError, TypeError):
        return None


def _i(s) -> int | None:
    v = _f(s)
    return int(v) if v is not None else None


def _load(name: str) -> list[dict]:
    p = _CSV_DIR / name
    if not p.exists():
        return []
    with p.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


@dataclass(frozen=True)
class CountrySector:
    country_iso3: str
    sector: str
    present: bool
    source_origin: str


@dataclass(frozen=True)
class PropagationPaper:
    paper_id: str
    title: str
    authors: str
    year: int | None
    journal: str
    doi: str
    mechanism: str
    key_quantitative_finding: str
    propagation_multiplier_estimate: float | None
    recovery_duration_estimate_months: int | None
    evidence_confidence: str
    source_origin: str


@dataclass(frozen=True)
class FinancialContagion:
    paper_id: str
    title: str
    authors: str
    year: int | None
    journal: str
    doi: str
    contagion_type: str
    key_finding: str
    spillover_coefficient_estimate: float | None
    scope: str
    evidence_confidence: str
    source_origin: str


@dataclass(frozen=True)
class Chokepoint:
    chokepoint_id: str
    name: str
    capacity_share_global_trade_pct: float | None
    capacity_share_global_seaborne_oil_pct: float | None
    capacity_share_global_seaborne_trade_pct: float | None
    tsmc_foundry_share_pct: float | None
    tsmc_advanced_chips_share_pct: float | None
    expected_annual_loss_usd_b: float | None
    rerouting_cost_per_day_usd_b: float | None
    failure_duration_observed_days: float | None
    failure_event_year: int | None
    failure_event_name: str
    downstream_sectors: tuple[str, ...]
    evidence_citation: str
    doi_or_url: str
    evidence_confidence: str
    source_origin: str


@dataclass(frozen=True)
class MechanismEvidence:
    mechanism: str
    label: str                      # SUPPORTED / UNCERTAIN / UNSUPPORTED
    evidence_strength: str          # STRONG / MODERATE / WEAK / ABSENT
    key_paper: str
    geds_assumption_used: str
    matches_evidence: str
    confidence: int | None
    source_origin: str


# ── load all CSVs ──────────────────────────────────────────────────────────

def _load_country_sectors() -> tuple[tuple[CountrySector, ...], dict[str, set[str]]]:
    rows = _load("country_sector_presence.csv")
    out = []
    by_country: dict[str, set[str]] = {}
    for r in rows:
        cs = CountrySector(
            country_iso3=r.get("country_iso3", ""),
            sector=r.get("sector", ""),
            present=r.get("present", "false").lower() == "true",
            source_origin=r.get("_source_origin", ""),
        )
        out.append(cs)
        if cs.present:
            by_country.setdefault(cs.country_iso3, set()).add(cs.sector)
    return tuple(out), by_country


def _load_propagation_papers() -> tuple[tuple[PropagationPaper, ...], dict[str, list[PropagationPaper]]]:
    rows = _load("propagation_literature.csv")
    out = []
    by_mech: dict[str, list[PropagationPaper]] = {}
    for r in rows:
        p = PropagationPaper(
            paper_id=r.get("paper_id", ""),
            title=r.get("title", ""),
            authors=r.get("authors", ""),
            year=_i(r.get("year")),
            journal=r.get("journal", ""),
            doi=r.get("doi", ""),
            mechanism=r.get("mechanism", ""),
            key_quantitative_finding=r.get("key_quantitative_finding", ""),
            propagation_multiplier_estimate=_f(r.get("propagation_multiplier_estimate")),
            recovery_duration_estimate_months=_i(r.get("recovery_duration_estimate_months")),
            evidence_confidence=r.get("evidence_confidence", ""),
            source_origin=r.get("_source_origin", ""),
        )
        out.append(p)
        by_mech.setdefault(p.mechanism, []).append(p)
    return tuple(out), by_mech


def _load_financial() -> tuple[tuple[FinancialContagion, ...], dict[str, FinancialContagion]]:
    rows = _load("financial_contagion.csv")
    out = []
    for r in rows:
        out.append(FinancialContagion(
            paper_id=r.get("paper_id", ""),
            title=r.get("title", ""),
            authors=r.get("authors", ""),
            year=_i(r.get("year")),
            journal=r.get("journal", ""),
            doi=r.get("doi", ""),
            contagion_type=r.get("contagion_type", ""),
            key_finding=r.get("key_finding", ""),
            spillover_coefficient_estimate=_f(r.get("spillover_coefficient_estimate")),
            scope=r.get("scope", ""),
            evidence_confidence=r.get("evidence_confidence", ""),
            source_origin=r.get("_source_origin", ""),
        ))
    by_id = {x.paper_id: x for x in out}
    return tuple(out), by_id


def _load_chokepoints() -> tuple[tuple[Chokepoint, ...], dict[str, Chokepoint]]:
    rows = _load("global_chokepoints.csv")
    out = []
    for r in rows:
        out.append(Chokepoint(
            chokepoint_id=r.get("chokepoint_id", ""),
            name=r.get("name", ""),
            capacity_share_global_trade_pct=_f(r.get("capacity_share_global_trade_pct")),
            capacity_share_global_seaborne_oil_pct=_f(r.get("capacity_share_global_seaborne_oil_pct")),
            capacity_share_global_seaborne_trade_pct=_f(r.get("capacity_share_global_seaborne_trade_pct")),
            tsmc_foundry_share_pct=_f(r.get("tsmc_foundry_share_pct")),
            tsmc_advanced_chips_share_pct=_f(r.get("tsmc_advanced_chips_share_pct")),
            expected_annual_loss_usd_b=_f(r.get("expected_annual_loss_usd_b")),
            rerouting_cost_per_day_usd_b=_f(r.get("rerouting_cost_per_day_usd_b")),
            failure_duration_observed_days=_f(r.get("failure_duration_observed_days")),
            failure_event_year=_i(r.get("failure_event_year")),
            failure_event_name=r.get("failure_event_name", ""),
            downstream_sectors=tuple(s.strip() for s in r.get("downstream_sectors", "").split(";") if s.strip()),
            evidence_citation=r.get("evidence_citation", ""),
            doi_or_url=r.get("doi_or_url", ""),
            evidence_confidence=r.get("evidence_confidence", ""),
            source_origin=r.get("_source_origin", ""),
        ))
    by_id = {x.chokepoint_id: x for x in out}
    return tuple(out), by_id


def _load_mechanism() -> tuple[tuple[MechanismEvidence, ...], dict[str, MechanismEvidence]]:
    rows = _load("mechanism_validation.csv")
    out = []
    for r in rows:
        out.append(MechanismEvidence(
            mechanism=r.get("mechanism", ""),
            label=r.get("label", ""),
            evidence_strength=r.get("evidence_strength", ""),
            key_paper=r.get("key_paper", ""),
            geds_assumption_used=r.get("geds_assumption_used", ""),
            matches_evidence=r.get("matches_evidence", ""),
            confidence=_i(r.get("confidence")),
            source_origin=r.get("_source_origin", ""),
        ))
    return tuple(out), {x.mechanism: x for x in out}


# Module-level loaded data
COUNTRY_SECTORS, _COUNTRY_TO_SECTORS = _load_country_sectors()
PROPAGATION_PAPERS, _PAPERS_BY_MECH = _load_propagation_papers()
FINANCIAL, _FINANCIAL_BY_ID = _load_financial()
CHOKEPOINTS, _CHOKEPOINT_BY_ID = _load_chokepoints()
MECHANISMS, _MECH_BY_NAME = _load_mechanism()


# ── lookup helpers ────────────────────────────────────────────────────────


def country_has_sector(iso3: str, sector: str) -> bool | None:
    """Phase 2 contract: NEVER invent. Returns None if the (country, sector)
    pair is not in the CSV (UNKNOWN per user spec).
    """
    sectors = _COUNTRY_TO_SECTORS.get(iso3)
    if sectors is None:
        return None  # UNKNOWN — country not in registry
    return sector in sectors


def get_country_present_sectors(iso3: str) -> tuple[str, ...] | None:
    sectors = _COUNTRY_TO_SECTORS.get(iso3)
    return tuple(sorted(sectors)) if sectors is not None else None


def get_propagation_papers(mechanism: str) -> tuple[PropagationPaper, ...]:
    return tuple(_PAPERS_BY_MECH.get(mechanism, ()))


def get_chokepoint(chokepoint_id: str) -> Chokepoint | None:
    return _CHOKEPOINT_BY_ID.get(chokepoint_id)


def get_mechanism_evidence(mechanism: str) -> MechanismEvidence | None:
    return _MECH_BY_NAME.get(mechanism)


def supported_mechanisms() -> tuple[MechanismEvidence, ...]:
    return tuple(m for m in MECHANISMS if m.label == "SUPPORTED")


def unsupported_mechanisms() -> tuple[MechanismEvidence, ...]:
    return tuple(m for m in MECHANISMS if m.label == "UNSUPPORTED")


def uncertain_mechanisms() -> tuple[MechanismEvidence, ...]:
    return tuple(m for m in MECHANISMS if m.label == "UNCERTAIN")


__all__ = [
    "CountrySector", "PropagationPaper", "FinancialContagion",
    "Chokepoint", "MechanismEvidence",
    "COUNTRY_SECTORS", "PROPAGATION_PAPERS", "FINANCIAL",
    "CHOKEPOINTS", "MECHANISMS",
    "country_has_sector", "get_country_present_sectors",
    "get_propagation_papers", "get_chokepoint",
    "get_mechanism_evidence",
    "supported_mechanisms", "unsupported_mechanisms", "uncertain_mechanisms",
]
