import type { AdvisorResult, GraphSnapshot, Scenario, SimulationResult } from "./types";

const API = (process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000").replace(/\/$/, "");
const WS = (process.env.NEXT_PUBLIC_WS_URL || "ws://127.0.0.1:8000").replace(/\/$/, "");

/** Single source of truth for the backend base URL — import this, don't re-derive it. */
export const API_BASE = API;

// ─── offline snapshot fallback ──────────────────────────────────────────────
//
// The backend sleeps after 15 min on free-tier hosting and takes 20-30 s to
// wake. Nearly every panel renders `null` until its fetch resolves, so someone
// arriving at a cold instance used to see a title and empty space, with no
// signal the page would ever fill in.
//
// So the build ships `public/snapshot/*.json`: the exact responses the
// deterministic endpoints return on this commit, generated by
// backend/scripts/build_frontend_snapshot.py and pinned by
// backend/tests/test_frontend_snapshot.py, which fails if the committed files
// drift from what the API actually returns.
//
// When a live call fails — network error OR non-2xx — the client serves the
// snapshot, flips `snapshotActive`, and the connection banner states plainly
// that the numbers on screen are precomputed and names the commit. Nothing is
// invented and nothing is silently substituted: it is the same model output,
// arriving from disk instead of over the wire, and labelled as such.
//
// Endpoints whose answers depend on wall-clock time or on an LLM are NOT
// snapshotted, so those panels stay empty while the backend is down. A frozen
// "current news signal" or "last refreshed" would be a false claim, which is
// worse than a blank panel.

/** Request path -> snapshot filename stem. Must stay byte-identical to `slug()`
 *  in backend/scripts/build_frontend_snapshot.py; a test pins the two together. */
export function snapshotKey(path: string): string {
  return path.replace(/^\/+|\/+$/g, "").replace(/[^a-zA-Z0-9._-]+/g, "_");
}

let snapshotActive = false;
const snapshotListeners = new Set<() => void>();

/** True once any response on this page has been served from the static snapshot. */
export const isSnapshotActive = () => snapshotActive;
export const isSnapshotActiveServer = () => false;

export function subscribeSnapshot(fn: () => void): () => void {
  snapshotListeners.add(fn);
  return () => { snapshotListeners.delete(fn); };
}

async function fromSnapshot<T>(key: string): Promise<T> {
  const res = await fetch(`/snapshot/${key}.json`);
  if (!res.ok) throw new Error(`snapshot ${key} → ${res.status}`);
  const data = (await res.json()) as T;
  if (!snapshotActive) {
    snapshotActive = true;
    snapshotListeners.forEach((fn) => fn());
  }
  return data;
}

export interface SnapshotManifest {
  commit: string;
  commit_short: string;
  commit_date: string;
  flagship_scenario: string;
  files: string[];
  note: string;
}

async function getJson<T>(path: string): Promise<T> {
  try {
    const res = await fetch(`${API}${path}`);
    if (!res.ok) throw new Error(`GET ${path} → ${res.status}`);
    return (await res.json()) as T;
  } catch (err) {
    // Rethrow the ORIGINAL error when no snapshot covers this path, so a
    // caller's catch block still sees why the live call failed rather than a 404
    // on a file that was never meant to exist.
    return fromSnapshot<T>(snapshotKey(path)).catch(() => { throw err; });
  }
}

async function postJson<T>(path: string, body: unknown): Promise<T> {
  try {
    const res = await fetch(`${API}${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(`POST ${path} → ${res.status}`);
    return (await res.json()) as T;
  } catch (err) {
    // Only baked scenarios have an honest precomputed answer. A custom scenario
    // must never be served someone else's cascade.
    const sid = (body as { scenario_id?: unknown } | null)?.scenario_id;
    if (typeof sid !== "string") throw err;
    return fromSnapshot<T>(`post_${snapshotKey(path)}__${snapshotKey(sid)}`)
      .catch(() => { throw err; });
  }
}

/** GET through the snapshot-aware client. For endpoints with no typed helper. */
export const getRaw = <T,>(path: string): Promise<T> => getJson<T>(path);

async function deleteJson<T>(path: string): Promise<T> {
  const res = await fetch(`${API}${path}`, { method: "DELETE" });
  if (!res.ok) throw new Error(`DELETE ${path} → ${res.status}`);
  return res.json();
}

// ─── model comparison + forecast band (Tasks #4/#5) ─────────────────────────

export interface BaselineModel {
  model: string;
  industry_loss: number;
  recovery_weeks: number;
  parameters: number;
}
export interface BaselineCompare {
  industry: string;
  models: BaselineModel[];
}
export interface ForecastBand {
  n_folds: number;
  metric: string;
  available: boolean;
  median?: number;
  p10?: number;
  p90?: number;
  min?: number;
  max?: number;
  rel_width?: number;
}

// ─── Grok narrative ────────────────────────────────────────────────────────

export interface PolicyRec {
  action: string;
  target: string;
  time_horizon_weeks: number;
}

export interface GrokNarrative {
  scenario_id: string;
  lang: "en" | "ru";
  model: string;
  cached: boolean;
  latency_ms: number;
  confidence: "low" | "medium" | "high";
  executive_summary: string;
  cascade_mechanism: string;
  immediate_risks: string[];
  structural_vulnerabilities: string[];
  policy_recommendations: PolicyRec[];
  overlay_active: boolean;
  overlay_node_count: number;
}

// ─── News pipeline ─────────────────────────────────────────────────────────

export interface NewsDelta {
  node_id: string;
  vulnerability_delta: number;
  d_eff_multiplier: number;
  decay_weeks: number;
  confidence: number;
}

export interface NewsEvent {
  headline: {
    title: string;
    description: string;
    source: string;
    url: string;
    published_at: string;
  };
  event_type: "strike" | "conflict" | "disaster" | "policy" | "logistics" | "unknown";
  matched_nodes: string[];
  entities: string[];
  deltas: NewsDelta[];
}

export interface NewsRecentResponse {
  n_events: number;
  lang: "en" | "ru";
  /** "live" = fetched from NewsAPI/GNews; "stub" = labelled demo data (no API key). */
  mode: "live" | "stub";
  events: NewsEvent[];
}

export interface NewsOverlayState {
  active: boolean;
  applied_at?: string;
  active_until?: string;
  n_nodes_affected: number;
  deltas: Record<string, { vuln_delta: number; d_eff_multiplier: number; confidence: number; source: string; event_type: string }>;
}

// ─── Validation / track record ─────────────────────────────────────────────

export interface CVReport {
  method: string;
  n_events: number;
  runtime_seconds: number;
  pass_rate_25pct: number;
  pass_rate_25pct_ci95_lo: number;
  pass_rate_25pct_ci95_hi: number;
  pass_rate_50pct: number;
  pass_rate_50pct_ci95_lo: number;
  pass_rate_50pct_ci95_hi: number;
  mae_industry_loss: number;
  mae_inflation: number;
  mae_recovery_weeks: number;
  pearson_loss: number;
  spearman_loss: number;
  rmse_normalized: number;
  timestamp: string;
}

// ─── Crisis radar (Claude) ───────────────────────────────────────────────────

export interface CrisisScenario {
  title_en: string; title_ru: string;
  trigger_en: string; trigger_ru: string;
  mechanism_en: string; mechanism_ru: string;
  watch_en: string; watch_ru: string;
  basis: string;
  severity: "low" | "medium" | "high";
}

export interface CrisisRadarResult {
  overview_en: string; overview_ru: string;
  scenarios: CrisisScenario[];
  disclaimer_en: string; disclaimer_ru: string;
  model: string;
  cached: boolean;
  latency_ms: number;
  /** "live" = real Claude call; "stub" = no ANTHROPIC_API_KEY (labelled demo). */
  mode: "live" | "stub";
  configured: boolean;
  n_signals: number;
  active_news_count: number;
}

// ─── API client ────────────────────────────────────────────────────────────

/** One row of historical_events.csv, as served by /data/historical-events-csv. */
export interface HistoricalEvent {
  id: number;
  slug: string;
  name_ru: string;
  name_en: string;
  type: string;
  start_date: string;
  countries_iso3: string[];
  industries_geds: string[];
  shock_mechanism: string;
  delta_output_pct: number | null;
  recovery_weeks: number | null;
  in_geds_graph: boolean;
  target_node_geds: string | null;
  shock_magnitude_geds: number | null;
  duration_weeks_geds: number | null;
  sources: string[];
  notes: string;
}

export interface HistoricalEventsResponse {
  n_total: number;
  n_in_graph: number;
  n_out_of_graph: number;
  events: HistoricalEvent[];
}

/** One scored event from /cascade-validation — what the model said vs what happened. */
export interface CascadeEventResult {
  slug: string;
  name: string;
  is_chokepoint: boolean;
  predicted_recovery_weeks: number;
  observed_recovery_weeks: number | null;
  /** simulated window length; a prediction equal to it is a lower bound */
  horizon_weeks: number;
  /** true when the node never recovered in-window — NOT a prediction */
  recovery_censored: boolean;
  dims: { name: string; predicted: number; observed: number; abs_error: number }[];
}

export interface CascadeValidation {
  shape: {
    events: CascadeEventResult[];
    mae_by_dim: Record<string, number>;
    spearman_by_dim: Record<string, number>;
    n_by_dim: Record<string, number>;
  };
}

export const api = {
  /** Provenance for whatever the snapshot fallback served. Static file, no backend. */
  snapshotManifest: async (): Promise<SnapshotManifest | null> => {
    try {
      const res = await fetch("/snapshot/manifest.json");
      return res.ok ? ((await res.json()) as SnapshotManifest) : null;
    } catch {
      return null;
    }
  },
  historicalEvents: (): Promise<HistoricalEventsResponse> =>
    getJson("/api/v1/data/historical-events-csv"),
  cascadeValidation: (): Promise<CascadeValidation> =>
    getJson("/api/v1/cascade-validation"),
  graph: (version: "v2" | "v3" = "v2"): Promise<GraphSnapshot> =>
    getJson(version === "v3" ? "/api/v1/graph?version=v3" : "/api/v1/graph"),
  scenarios: (): Promise<Scenario[]> => getJson("/api/v1/scenarios"),
  scenario: (id: string): Promise<Scenario> => getJson(`/api/v1/scenarios/${id}`),
  simulate: (req: { scenario_id?: string; custom?: unknown }): Promise<SimulationResult> =>
    postJson("/api/v1/simulate", req),
  baselineCompare: (req: { scenario_id?: string; custom?: unknown }): Promise<BaselineCompare> =>
    postJson("/api/v1/baseline-compare", req),
  forecastBand: (req: { scenario_id?: string; custom?: unknown }): Promise<ForecastBand> =>
    postJson("/api/v1/forecast-band", req),
  policy: (req: { scenario_id?: string; custom?: unknown }): Promise<AdvisorResult> =>
    postJson("/api/v1/policy", req),
  wsStreamUrl: () => `${WS}/ws/simulate`,

  // Liveness probe — root-level (/healthz), not under /api/v1.
  //
  // Returns true if the backend HOST is reachable — i.e. it answered with *any*
  // HTTP status. We deliberately do NOT require 2xx: a stale deploy that 404s on
  // /healthz, or a 500, still proves the server is up and the data endpoints may
  // work. Only a network-level failure (connection refused, DNS, CORS block, or
  // timeout) — where fetch() itself rejects — counts as offline, so the banner
  // can't false-fire against a reachable-but-imperfect backend.
  healthz: async (): Promise<boolean> => {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 8000);
    try {
      await fetch(`${API}/healthz`, { signal: ctrl.signal });
      return true; // any HTTP response means the host is reachable
    } catch {
      return false; // network error / timeout → genuinely unreachable
    } finally {
      clearTimeout(timer);
    }
  },

  // Grok narrative
  narrative: (req: {
    scenario_id?: string;
    custom?: unknown;
    lang?: "en" | "ru";
    force_refresh?: boolean;
  }): Promise<GrokNarrative> => postJson("/api/v1/narrative", req),

  // Crisis radar — Claude-analyzed danger scenarios (bilingual), grounded in GEDS signals
  crisisRadar: (req: { force_refresh?: boolean } = {}): Promise<CrisisRadarResult> =>
    postJson("/api/v1/crisis-radar", req),

  // News pipeline
  newsRecent: (lang: "en" | "ru" = "en", use_stub = false): Promise<NewsRecentResponse> =>
    getJson(`/api/v1/news/recent?lang=${lang}&use_stub=${use_stub}`),
  newsApply: (req: {
    use_stub?: boolean;
    decay_hours?: number;
    confidence_floor?: number;
    lang?: "en" | "ru";
  }): Promise<{ applied_at: string; active_until: string; n_nodes_affected: number; deltas: Record<string, unknown>; mode: "live" | "stub" }> =>
    postJson("/api/v1/news/apply", req),
  newsOverlay: (): Promise<NewsOverlayState> => getJson("/api/v1/news/overlay"),
  newsOverlayClear: (): Promise<{ cleared: boolean }> => deleteJson("/api/v1/news/overlay"),

  // Validation / track record (used by the truthful badge)
  cvReport: (): Promise<CVReport> => getJson("/api/v1/cv-report"),

  // Data freshness (populated by GitHub Actions daily refresh)
  lastRefresh: (): Promise<{
    last_refresh_utc: string | null;
    age_hours: number | null;
    source: string;
    workflow_run_url?: string | null;
  }> => getJson("/api/v1/data/last-refresh"),
};
