"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Lang = "en" | "ru";

// ── simple string translations ───────────────────────────────────────────────

export const T = {
  en: {
    appTitle: "GEDS",
    appSubtitle: "Global Economic Dependency Simulator",
    appTagline:
      "Modeling supply-chain fragility before it cascades — research-grade simulation backed by UN Comtrade, World Bank & OECD data.",
    dataStamp: "UN Comtrade 2019 · WB LPI 2018 · OECD STAN · IMF WEO",
    validationBadge: "Live validation · loading…",   // populated at runtime by StatusRibbon from /api/v1/cv-report
    nodes: "nodes",
    edges: "edges",
    loadingGraph: "loading graph…",
    streamingWeek: "streaming week",
    framesLoaded: "frames",
    idle: "idle",
    langBtn: "RU",
    faqBtn: "FAQ",

    // Scenario panel
    presets: "Preset scenarios",
    selectedScenario: "Selected scenario",
    shocks: "Shocks",
    horizon: "Horizon",
    weeks: "weeks",
    runBtn: "Run simulation",
    runningBtn: "Running…",

    // Metrics panel
    simulationResults: "Simulation results",
    summary: "Summary",
    peakCSI: "Peak CSI",
    peakCSIDesc:
      "Cascade Severity Index — network-average shock, each node weighted by its centrality, supplier dependence, fragility and recovery speed. 0 = no disruption, 1 = total collapse.",
    peakECV: "Peak ECV",
    peakECVDesc:
      "Economic Contagion Velocity — how fast the shock is spreading (new disrupted GDP-units per week).",
    finalCSI: "Final CSI",
    finalCSIDesc: "Residual system stress at the end of the simulation horizon.",
    outputLoss: "Total output loss",
    topInflation: "Highest inflation",
    topGDPImpact: "Largest GDP hit",
    countriesAffected: "Countries affected",
    globalRecovery: "Global recovery",
    countryRisk: "Country risk",
    sectorFragility: "Sector fragility",
    recov: "recovery",
    noResults:
      "Results appear here after a simulation completes. Select a scenario on the left and click Run.",

    // Policy advisor
    policyAdvisor: "Policy advisor",
    analyseBtn: "Analyse",
    analysingBtn: "Analysing…",
    runFirstHint: "Run a simulation first, then click Analyse",
    noResultsHint:
      "Run a simulation then click Analyse for AI-generated policy recommendations.",
    executiveSummary: "Executive summary",
    interventionWindow: "Intervention window",
    criticalNodes: "critical nodes",
    chopointAlerts: "Chokepoint alerts",
    recommendations: "Recommendations",
    estimatedImpact: "Est. risk reduction",
    implDifficulty: "Impl. difficulty",
    targetCountries: "Countries",
    targetIndustries: "Industries",
    weeksToEffect: "w to effect",
    methodologyTitle: "Methodology & data sources",
    methodologyText:
      "Recommendations are generated by a rule-based engine from simulation evidence: peak shock thresholds, network centrality rankings, and supply shortage probabilities. All model parameters derive from UN Comtrade 2019, World Bank LPI 2018, and OECD STAN sector shares. Current out-of-sample validation correlation and pass-rate are shown live in the top-right badge — see /api/v1/cv-report for the full leave-one-out cross-validation report with bootstrap confidence intervals.",
    sourcesLabel: "Primary sources",
    confidenceLabel: "Model confidence",
    confidenceValue: "See live validation badge (top-right) and /api/v1/cv-report",
    actWithin: "Act within",

    // Priority labels
    critical: "Critical",
    high: "High",
    medium: "Medium",
    low: "Low",

    // Category labels
    emergency: "Emergency",
    diversification: "Diversification",
    stockpiling: "Stockpiling",
    diplomatic: "Diplomatic",
    infrastructure: "Infrastructure",
    monetary: "Monetary",

    // Footer
    footerLine1:
      "Flagship scenario: Taiwan semiconductor exports fall 70–80%. Watch the cascade ripple through automotive, electronics, and consumer goods across 12 economies in real time.",
    footerLine2:
      "Two novel metrics: Cascade Severity Index (CSI) — network-average shock weighted by each node's centrality and fragility — and Economic Contagion Velocity (ECV) — the weekly rate at which new nodes enter disruption. Validated against 27 primary-sourced historical events (1999–2023), including the COVID semiconductor shortage (2020–21), the Suez Canal blockage (2021), Japan's triple disaster (2011), and the 2008–09 financial crisis.",
    footerLine3:
      "Use the overlay selector in the timeline to switch between shock intensity, inflation pressure, output loss, and unemployment risk. Click Analyse after any simulation for prioritized policy recommendations.",

    // FAQ
    faqTitle: "Frequently asked questions",
    faqClose: "Close",

    // Grok narrative panel
    narrativeTitle: "AI Policy Analysis",
    narrativeSubtitle: "Grok-generated narrative · synthesizes the simulation into context",
    narrativeLoading: "Generating analysis…",
    narrativeError: "Failed to generate analysis. Check that the backend is running.",
    narrativeExecutiveSummary: "Executive summary",
    narrativeCascadeMechanism: "Cascade mechanism",
    narrativeImmediateRisks: "Immediate risks (1–4 weeks)",
    narrativeStructural: "Structural vulnerabilities",
    narrativePolicyRecs: "Policy recommendations",
    narrativeConfidence: "Confidence",
    narrativeConfLow: "low",
    narrativeConfMedium: "medium",
    narrativeConfHigh: "high",
    narrativeCached: "cached",
    narrativeLive: "live",
    narrativeStub: "stub (no API key)",
    narrativeOverlayActive: "Live news overlay applied",
    narrativeOverlayInactive: "No news overlay applied",
    narrativeRefresh: "Refresh analysis",
    narrativeHorizon: "weeks",
    narrativeRunFirst: "Run a simulation first to generate an AI analysis.",
    narrativeTarget: "Target",

    // News signals panel
    newsTitle: "Live News Signals",
    newsSubtitle: "Real-time disruption events mapped to graph nodes",
    newsRefresh: "Refresh",
    newsApply: "Apply to next simulation",
    newsClear: "Clear overlay",
    newsApplied: "Applied",
    newsNoEvents: "No relevant disruption events detected.",
    newsLoading: "Fetching news…",
    newsStubMode: "Stub mode (no API key configured)",
    newsLiveMode: "Live mode",
    newsOverlayHeader: "Active overlay",
    newsOverlayNone: "No overlay active. Simulations use the baseline graph.",
    newsOverlayActiveUntil: "Active until",
    newsAffectedNodes: "nodes affected",
    newsEventStrike: "Labor strike",
    newsEventConflict: "Conflict / sanctions",
    newsEventDisaster: "Natural disaster",
    newsEventPolicy: "Policy / tariff",
    newsEventLogistics: "Logistics disruption",
    newsEventUnknown: "Other",
    newsMatchedNodes: "Matched nodes",
    newsDelta: "Suggested delta",
    newsConfidence: "confidence",
  },

  ru: {
    appTitle: "GEDS",
    appSubtitle: "Симулятор глобальных экономических зависимостей",
    appTagline:
      "Моделирование хрупкости цепочек поставок до начала каскадного распространения — научная симуляция на основе данных ООН Comtrade, Всемирного банка и ОЭСР.",
    dataStamp: "ООН Comtrade 2019 · ВБ LPI 2018 · ОЭСР STAN · МВФ МЭП",
    validationBadge: "Live-валидация · загрузка…",   // заполняется на лету из /api/v1/cv-report
    nodes: "узлов",
    edges: "связей",
    loadingGraph: "загрузка графа…",
    streamingWeek: "поток, неделя",
    framesLoaded: "кадров",
    idle: "ожидание",
    langBtn: "EN",
    faqBtn: "FAQ",

    presets: "Готовые сценарии",
    selectedScenario: "Выбранный сценарий",
    shocks: "Шоки",
    horizon: "Горизонт",
    weeks: "нед.",
    runBtn: "Запустить симуляцию",
    runningBtn: "Выполняется…",

    simulationResults: "Результаты симуляции",
    summary: "Итоги",
    peakCSI: "Пик CSI",
    peakCSIDesc:
      "Индекс серьёзности каскада — средний по сети шок, где каждый узел взвешен своей важностью в сети, зависимостью от поставщиков, хрупкостью и скоростью восстановления. 0 = нет нарушений, 1 = полный коллапс.",
    peakECV: "Пик ECV",
    peakECVDesc:
      "Скорость экономического заражения — как быстро распространяется шок (новые нарушенные единицы ВВП в неделю).",
    finalCSI: "Финальный CSI",
    finalCSIDesc: "Остаточный системный стресс в конце горизонта симуляции.",
    outputLoss: "Общие потери выпуска",
    topInflation: "Наибольшая инфляция",
    topGDPImpact: "Наибольший удар по ВВП",
    countriesAffected: "Стран затронуто",
    globalRecovery: "Глобальное восстановление",
    countryRisk: "Риск по странам",
    sectorFragility: "Хрупкость секторов",
    recov: "восст.",
    noResults:
      "Результаты появятся после завершения симуляции. Выберите сценарий слева и нажмите «Запустить».",

    policyAdvisor: "Советник по политике",
    analyseBtn: "Анализировать",
    analysingBtn: "Анализ…",
    runFirstHint: "Сначала запустите симуляцию, затем нажмите «Анализировать»",
    noResultsHint:
      "Запустите симуляцию, затем нажмите «Анализировать» для получения рекомендаций.",
    executiveSummary: "Краткое резюме",
    interventionWindow: "Окно вмешательства",
    criticalNodes: "критических узлов",
    chopointAlerts: "Предупреждения о проливах",
    recommendations: "Рекомендации",
    estimatedImpact: "Оценка снижения риска",
    implDifficulty: "Сложность реализации",
    targetCountries: "Страны",
    targetIndustries: "Отрасли",
    weeksToEffect: "нед. до эффекта",
    methodologyTitle: "Методология и источники данных",
    methodologyText:
      "Рекомендации генерируются системой правил на основе данных симуляции: пороги пиковых шоков, рейтинги сетевой центральности и вероятности дефицита поставок. Все параметры модели взяты из ООН Comtrade 2019, ВБ LPI 2018 и долей секторов ОЭСР STAN. Текущая корреляция и доля попаданий на данных вне выборки показаны вживую в значке справа сверху — полный отчёт о LOO-кросс-валидации с бутстреп-доверительными интервалами доступен по /api/v1/cv-report.",
    sourcesLabel: "Первичные источники",
    confidenceLabel: "Достоверность модели",
    confidenceValue: "См. live-значок валидации (справа сверху) и /api/v1/cv-report",
    actWithin: "Действовать в течение",

    critical: "Критический",
    high: "Высокий",
    medium: "Средний",
    low: "Низкий",

    emergency: "Экстренный",
    diversification: "Диверсификация",
    stockpiling: "Запасы",
    diplomatic: "Дипломатия",
    infrastructure: "Инфраструктура",
    monetary: "Монетарный",

    footerLine1:
      "Флагманский сценарий: экспорт полупроводников из Тайваня падает на 70–80%. Наблюдайте в реальном времени, как каскад распространяется через автомобильную, электронную промышленность и потребительские товары 12 стран.",
    footerLine2:
      "Два новых показателя: Индекс серьёзности каскада (CSI) — средний по сети шок, взвешенный важностью и хрупкостью каждого узла — и Скорость экономического заражения (ECV) — доля новых узлов, входящих в нарушение за неделю. Проверено на 27 исторических событиях с первичными источниками (1999–2023): дефицит чипов COVID (2020–21), Суэц (2021), тройная катастрофа в Японии (2011), финансовый кризис 2008–09.",
    footerLine3:
      "Используйте переключатель наложения на шкале времени для просмотра шока, инфляции, потерь выпуска и безработицы. Нажмите «Анализировать» после симуляции для получения приоритетных рекомендаций.",

    faqTitle: "Часто задаваемые вопросы",
    faqClose: "Закрыть",

    // Grok narrative panel
    narrativeTitle: "AI-анализ политики",
    narrativeSubtitle: "Сгенерировано Grok · превращает данные симуляции в контекстный анализ",
    narrativeLoading: "Генерация анализа…",
    narrativeError: "Не удалось получить анализ. Проверьте, запущен ли backend.",
    narrativeExecutiveSummary: "Краткое резюме",
    narrativeCascadeMechanism: "Механизм каскада",
    narrativeImmediateRisks: "Срочные риски (1–4 недели)",
    narrativeStructural: "Структурные уязвимости",
    narrativePolicyRecs: "Рекомендации политики",
    narrativeConfidence: "Уверенность",
    narrativeConfLow: "низкая",
    narrativeConfMedium: "средняя",
    narrativeConfHigh: "высокая",
    narrativeCached: "из кэша",
    narrativeLive: "live",
    narrativeStub: "заглушка (нет API-ключа)",
    narrativeOverlayActive: "Применён слой live-новостей",
    narrativeOverlayInactive: "Слой новостей не применён",
    narrativeRefresh: "Обновить анализ",
    narrativeHorizon: "нед.",
    narrativeRunFirst: "Сначала запустите симуляцию для генерации AI-анализа.",
    narrativeTarget: "Адресат",

    // News signals panel
    newsTitle: "Live-сигналы новостей",
    newsSubtitle: "События в реальном времени, привязанные к узлам графа",
    newsRefresh: "Обновить",
    newsApply: "Применить к следующей симуляции",
    newsClear: "Снять слой",
    newsApplied: "Применено",
    newsNoEvents: "Релевантных событий не обнаружено.",
    newsLoading: "Загрузка новостей…",
    newsStubMode: "Демо-режим (API-ключ не задан)",
    newsLiveMode: "Live-режим",
    newsOverlayHeader: "Активный слой",
    newsOverlayNone: "Слой не активен. Симуляции используют базовый граф.",
    newsOverlayActiveUntil: "Действует до",
    newsAffectedNodes: "узлов затронуто",
    newsEventStrike: "Забастовка",
    newsEventConflict: "Конфликт / санкции",
    newsEventDisaster: "Стихийное бедствие",
    newsEventPolicy: "Политика / тарифы",
    newsEventLogistics: "Логистическое нарушение",
    newsEventUnknown: "Иное",
    newsMatchedNodes: "Совпадающие узлы",
    newsDelta: "Предлагаемое изменение",
    newsConfidence: "уверенность",
  },
} as const;

export type TKey = keyof typeof T.en;

// ── FAQ structured content ───────────────────────────────────────────────────

export interface FAQItem { q: string; a: string }
export interface FAQSection { title: string; items: FAQItem[] }

export const FAQ: Record<Lang, FAQSection[]> = {
  en: [
    {
      title: "The Basics",
      items: [
        {
          q: "What is GEDS?",
          a: "GEDS (Global Economic Dependency Simulator) is a scientific simulation platform that models how economic shocks — a blocked shipping lane, a factory closure, a trade war — spread through the global supply-chain network. It lets you run 'what if' scenarios and watch, week by week, which countries and industries get hit hardest and how long recovery takes.",
        },
        {
          q: "Who is this for?",
          a: "Policy analysts, economists, students, journalists, and anyone curious about global supply-chain fragility. The flagship scenario — Taiwan semiconductor disruption — is one of the most discussed systemic risks of our era. No economics background required.",
        },
        {
          q: "Is the data real or made up?",
          a: "Real primary data. Dependency weights come from UN Comtrade bilateral trade flows (2019). Country resilience comes from the World Bank Logistics Performance Index 2018. GDP values come from World Bank and IMF WEO (2019). Chokepoint vulnerability comes from IMO/Lloyd's List disruption statistics and IEA World Energy Outlook 2020.",
        },
      ],
    },
    {
      title: "How the simulation works",
      items: [
        {
          q: "What is a 'cascade'?",
          a: "When Taiwan's chip supply drops, chip-importing countries get hit first. Their automotive and electronics sectors slow down. This hits parts suppliers, which hits workers' spending, which hits consumer goods. Each round of impact is one 'wave' of the cascade. GEDS models these waves across 41 nodes in 12 countries, with horizons up to 104 weeks.",
        },
        {
          q: "What is the Cascade Severity Index (CSI)?",
          a: "CSI is a single number from 0 to 1 measuring how severely the entire network is disrupted. It is a network average where each node's contribution is weighted by its centrality in the network, its supplier dependence, its fragility and its recovery speed. CSI = 0 means no disruption; CSI = 1 would mean total economic collapse. In real historical events, peak CSI ranges from ~0.05 (Suez 2021) to ~0.35 (COVID semiconductor shortage).",
        },
        {
          q: "What is Economic Contagion Velocity (ECV)?",
          a: "ECV measures the speed of spreading — specifically, what share of the network's nodes newly enter significant disruption each week (a second variant measures how far from the origin the front has travelled). High ECV early in a scenario means the shock is accelerating. Falling ECV means the cascade is slowing. ECV is the key metric for timing policy interventions: act before ECV peaks.",
        },
        {
          q: "What is a 'dependency weight'?",
          a: "For each supply relationship — for example, Taiwan chips flowing into Japan's automotive sector — the dependency weight represents what fraction of Japan's automotive chip inputs come from Taiwan. Computed from UN Comtrade data as: (Japan imports of HS 8541+8542 from Taiwan) ÷ (Japan total imports of HS 8541+8542 from world). The higher the number, the more exposed that sector is.",
        },
        {
          q: "What are chokepoints?",
          a: "Chokepoints are geographic bottlenecks: the Taiwan Strait, Strait of Malacca, Suez Canal, and Strait of Hormuz. Roughly 40% of world trade by value flows through these four passages. Disrupting a chokepoint triggers shipping delays rather than production shutdowns — a different cascade pattern with faster onset but shorter duration.",
        },
      ],
    },
    {
      title: "Accuracy & trustworthiness",
      items: [
        {
          q: "How accurate are the predictions?",
          a: "Look at the live badge in the top-right and the full Validation page — every number there is computed live, never hardcoded. GEDS is tested with leave-one-event-out cross-validation (each historical event is predicted by a model that never saw it), with bootstrap 95% confidence intervals, currently on n=21 events. Be clear-eyed about what it is and isn't good at: when the event set was expanded from 8 to 21, rank correlation dropped substantially — the earlier strong ranking result was partly a small-sample artifact, and a simple linear-diffusion baseline currently beats GEDS on every benchmark metric. Absolute precision is also weak: the share of predictions landing within ±25% of the observed magnitude is low, and recovery-time estimates are not yet calibrated. So use GEDS for exploring cascade structure and relative comparison, not point forecasts. We publish the unflattering numbers on purpose — honest, reproducible validation is the entire point. Full report: /api/v1/cv-report.",
        },
        {
          q: "Where does the data come from?",
          a: "All parameters trace to published primary sources: (1) UN Comtrade 2019 API — bilateral trade flows; (2) World Bank LPI 2018 — logistics resilience index; (3) OECD STAN 2019 — sector GDP shares; (4) IMF WEO April 2020 — Taiwan GDP; (5) IEA World Energy Outlook 2020 — chokepoint exposure fractions; (6) IMO/Lloyd's List — disruption probabilities. Full provenance: GET /api/v1/data/provenance.",
        },
        {
          q: "Why might the model underpredict?",
          a: "Three known biases: (1) China's semiconductor dependency on Taiwan is understated by ~5pp because some Taiwan→China flows route through Hong Kong; (2) the US 'fabless' model creates IP-level dependency that raw import data misses; (3) just-in-time production means real shocks transmit faster than the weekly timestep captures. All documented in provenance.json.",
        },
        {
          q: "How is this different from other economic models?",
          a: "Most models are either too aggregate (country-level GDP) or too detailed (firm-level supply chains). GEDS operates at the meso-level: 12 key economies × 6 industries + chokepoints, parameterized from public trade data, running in real time in a browser. The combination of network visualization, real data provenance, and historical validation is what makes it distinctive.",
        },
      ],
    },
    {
      title: "Using the simulator",
      items: [
        {
          q: "How do I run a simulation?",
          a: "Select a preset scenario from the left panel (or build a custom one), then click 'Run simulation'. The map animates week by week. Use the timeline scrubber to jump to any week, and the overlay buttons to switch between Shock / Inflation / Output loss / Unemployment views. The right panel shows summary statistics once the run completes.",
        },
        {
          q: "What does the Policy Advisor do?",
          a: "After running a simulation, click 'Analyse'. The system analyzes peak shock values, network centrality, chokepoint alerts, and shortage probabilities, then generates prioritized recommendations — diversify suppliers, build strategic reserves, engage diplomatically, etc. Each recommendation shows estimated risk reduction, implementation difficulty, and time-to-effect.",
        },
        {
          q: "Can I build a custom scenario?",
          a: "Yes. Use the 'Custom scenario' section in the left panel. Add multiple shocks to any node — choose from 13 preset nodes (country-industry pairs and all 4 chokepoints), set the magnitude (5–100% disruption), start week, duration, and decay curve (step, linear, or exponential). This lets you model novel scenarios like a partial Taiwan disruption combined with a Malacca closure.",
        },
      ],
    },
  ],

  ru: [
    {
      title: "Основы",
      items: [
        {
          q: "Что такое GEDS?",
          a: "GEDS (Симулятор глобальных экономических зависимостей) — это научная платформа, которая моделирует, как экономические потрясения — блокировка морского пролива, закрытие завода, торговая война — распространяются по глобальной сети цепочек поставок. Вы можете запускать сценарии «что если» и наблюдать, неделя за неделей, какие страны и отрасли пострадают сильнее всего.",
        },
        {
          q: "Для кого это?",
          a: "Для аналитиков, экономистов, студентов, журналистов и всех, кому интересна хрупкость глобальных цепочек поставок. Флагманский сценарий — нарушение производства полупроводников на Тайване — один из самых обсуждаемых системных рисков нашего времени. Экономическое образование не требуется.",
        },
        {
          q: "Данные реальные или выдуманные?",
          a: "Реальные первичные данные. Веса зависимостей — из базы двусторонних торговых потоков ООН Comtrade (2019). Устойчивость стран — из Индекса логистики Всемирного банка (2018). ВВП — из Всемирного банка и МВФ (2019). Уязвимость морских проливов — из статистики IMO/Lloyd's List и МЭА.",
        },
      ],
    },
    {
      title: "Как работает симуляция",
      items: [
        {
          q: "Что такое «каскад»?",
          a: "Когда поставки тайваньских чипов падают, страны-импортёры страдают первыми. Их автозаводы и сборщики электроники замедляются. Это бьёт по поставщикам деталей, затем по потребительским расходам работников. Каждый круг последствий — одна «волна» каскада. GEDS моделирует такие волны по 41 узлу в 12 странах, с горизонтом до 104 недель.",
        },
        {
          q: "Что такое Индекс серьёзности каскада (CSI)?",
          a: "CSI — число от 0 до 1, показывающее, насколько серьёзно вся сеть нарушена в данный момент. Это средний по сети шок, где вклад каждого узла взвешен его важностью в сети (центральность), зависимостью от поставщиков, хрупкостью и скоростью восстановления. CSI = 0 — нет нарушений; CSI = 1 — полный экономический коллапс. На реальных событиях пик CSI: 0,05 (Суэц 2021) — 0,35 (дефицит чипов COVID).",
        },
        {
          q: "Что такое Скорость экономического заражения (ECV)?",
          a: "ECV измеряет скорость распространения — какая доля узлов сети впервые входит в значительное нарушение за неделю (второй вариант измеряет, как далеко от очага ушла волна). Высокий ECV в начале — шок ускоряется; падающий ECV — каскад замедляется. ECV — ключевой показатель для выбора момента вмешательства: действуйте до пика ECV.",
        },
        {
          q: "Что такое «вес зависимости»?",
          a: "Для каждых торговых отношений (например, тайваньские чипы → японский автопром) вес зависимости показывает, какую долю потребностей японского автопрома в чипах покрывает Тайвань. Вычисляется из данных ООН Comtrade: (импорт HS 8541+8542 из Тайваня) ÷ (весь импорт HS 8541+8542). Чем выше число, тем больше зависимость.",
        },
        {
          q: "Что такое узкие места (chokepoints)?",
          a: "Географические бутылочные горлышки: Тайваньский пролив, Малаккский пролив, Суэцкий канал и Ормузский пролив. Через них проходит ~40% мировой торговли. Нарушение пролива вызывает задержки доставки, а не остановку производства — другой тип каскада с более быстрым началом, но меньшей продолжительностью.",
        },
      ],
    },
    {
      title: "Точность и достоверность",
      items: [
        {
          q: "Насколько точны предсказания?",
          a: "Смотрите live-значок справа сверху и полную страницу «Валидация» — каждое число там вычисляется вживую, ничего не захардкожено. GEDS проверяется кросс-валидацией с исключением одного события (каждое историческое событие предсказывает модель, которая его не видела), с бутстреп-доверительными интервалами 95%, сейчас на n=21 событиях. Важно честно понимать сильные и слабые стороны: при расширении набора событий с 8 до 21 ранговая корреляция заметно упала — прежний сильный результат ранжирования был отчасти артефактом малой выборки, и простой baseline (линейная диффузия) сейчас обходит GEDS по всем метрикам бенчмарка. Абсолютная точность тоже слабая: доля прогнозов в пределах ±25% от наблюдаемой величины низкая, а время восстановления пока не откалибровано. Поэтому используйте GEDS для исследования структуры каскадов и относительного сравнения, а не для точечных прогнозов. Мы намеренно публикуем и неудобные цифры — честная воспроизводимая валидация и есть весь смысл. Полный отчёт: /api/v1/cv-report.",
        },
        {
          q: "Откуда берутся данные?",
          a: "Все параметры восходят к первичным источникам: (1) ООН Comtrade 2019 — двусторонние торговые потоки; (2) Всемирный банк LPI 2018 — логистическая устойчивость; (3) ОЭСР STAN 2019 — доли секторов в ВВП; (4) МВФ МЭП апрель 2020 — ВВП Тайваня; (5) МЭА World Energy Outlook 2020 — зависимость от проливов; (6) IMO/Lloyd's List — вероятности нарушений.",
        },
        {
          q: "Почему модель иногда недооценивает риск?",
          a: "Три известных систематических ошибки: (1) зависимость Китая от тайваньских чипов занижена на ~5 п.п. — часть потоков идёт через Гонконг; (2) американская «безфабричная» модель создаёт зависимость на уровне интеллектуальной собственности, не видимую в данных об импорте; (3) производство «точно в срок» распространяет шоки быстрее, чем недельный шаг модели.",
        },
      ],
    },
    {
      title: "Использование симулятора",
      items: [
        {
          q: "Как запустить симуляцию?",
          a: "Выберите готовый сценарий в левой панели (или создайте свой), затем нажмите «Запустить симуляцию». Карта оживёт, анимируя каскад по неделям. Используйте ползунок для перехода к любой неделе и кнопки наложения (Шок / Инфляция / Потери выпуска / Безработица) для переключения режима отображения.",
        },
        {
          q: "Что делает Советник по политике?",
          a: "После симуляции нажмите «Анализировать». Система анализирует пиковые шоки, центральность узлов, предупреждения о проливах и вероятности дефицита, затем генерирует приоритетные рекомендации — диверсификация поставщиков, стратегические резервы, дипломатия и т.д. Каждая рекомендация показывает оценку снижения риска, сложность реализации и время до эффекта.",
        },
        {
          q: "Можно ли создать свой сценарий?",
          a: "Да. Используйте раздел «Свой сценарий» в левой панели. Добавьте несколько шоков к любому узлу (13 вариантов, включая 4 морских пролива), задайте интенсивность (5–100%), начальную неделю, продолжительность и кривую затухания (ступень, линейное, экспоненциальное).",
        },
      ],
    },
  ],
};

// ── context ──────────────────────────────────────────────────────────────────

interface UIContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: TKey) => string;
  faqOpen: boolean;
  toggleFaq: () => void;
}

const UIContext = createContext<UIContextType>({
  lang: "en",
  toggleLang: () => {},
  t: (key) => T.en[key] as string,
  faqOpen: false,
  toggleFaq: () => {},
});

const LANG_KEY = "geds.lang";

export function UIProvider({ children }: { children: ReactNode }) {
  // Language must survive navigation: /validation is reached through a plain
  // <a href>, i.e. a full document load, so in-memory state alone reset every
  // visitor back to English and made the Russian validation copy unreachable.
  const [lang, setLang] = useState<Lang>("en");
  const [faqOpen, setFaqOpen] = useState(false);

  // Read after mount, not during render, so server and client markup match.
  useEffect(() => {
    try {
      const saved = window.localStorage.getItem(LANG_KEY);
      if (saved === "en" || saved === "ru") setLang(saved);
    } catch {
      /* storage blocked (private mode) — fall back to the default language */
    }
  }, []);

  const toggleLang = () =>
    setLang((l) => {
      const next: Lang = l === "en" ? "ru" : "en";
      try {
        window.localStorage.setItem(LANG_KEY, next);
      } catch {
        /* non-fatal: the toggle still works for this page view */
      }
      return next;
    });
  const toggleFaq = () => setFaqOpen((o) => !o);
  const t = (key: TKey) => (T[lang] as Record<string, string>)[key] ?? (T.en as Record<string, string>)[key] ?? key;
  return (
    <UIContext.Provider value={{ lang, toggleLang, t, faqOpen, toggleFaq }}>
      {children}
    </UIContext.Provider>
  );
}

export function useUI() {
  return useContext(UIContext);
}
